export interface Emoji {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
  unicode: string;
}

export const emojiCategories = ['All', 'Smileys & People', 'Animals & Nature', 'Food & Drink', 'Travel & Places', 'Activities', 'Objects', 'Symbols', 'Flags'] as const;

export type EmojiCategory = (typeof emojiCategories)[number];

export const emojis: Emoji[] = [
  // Smileys & People (20 items)
  { emoji: '😀', name: 'Grinning Face', category: 'Smileys & People', keywords: ['smile', 'happy', 'joy'], unicode: 'U+1F600' },
  { emoji: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys & People', keywords: ['smile', 'happy'], unicode: 'U+1F603' },
  { emoji: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys & People', keywords: ['smile', 'happy', 'joy'], unicode: 'U+1F604' },
  { emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys & People', keywords: ['smile', 'happy'], unicode: 'U+1F601' },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', category: 'Smileys & People', keywords: ['smile', 'happy', 'blush'], unicode: 'U+1F60A' },
  { emoji: '😍', name: 'Smiling Face with Heart-Eyes', category: 'Smileys & People', keywords: ['love', 'heart', 'smile'], unicode: 'U+1F60D' },
  { emoji: '🥰', name: 'Smiling Face with Hearts', category: 'Smileys & People', keywords: ['love', 'smile', 'hearts'], unicode: 'U+1F970' },
  { emoji: '😘', name: 'Face Blowing a Kiss', category: 'Smileys & People', keywords: ['kiss', 'love', 'heart'], unicode: 'U+1F618' },
  { emoji: '😂', name: 'Face with Tears of Joy', category: 'Smileys & People', keywords: ['laugh', 'cry', 'joy'], unicode: 'U+1F602' },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys & People', keywords: ['laugh', 'lol', 'rofl'], unicode: 'U+1F923' },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', category: 'Smileys & People', keywords: ['cool', 'sunglasses'], unicode: 'U+1F60E' },
  { emoji: '🤔', name: 'Thinking Face', category: 'Smileys & People', keywords: ['think', 'hmm', 'consider'], unicode: 'U+1F914' },
  { emoji: '😢', name: 'Crying Face', category: 'Smileys & People', keywords: ['sad', 'cry', 'tear'], unicode: 'U+1F622' },
  { emoji: '😭', name: 'Loudly Crying Face', category: 'Smileys & People', keywords: ['cry', 'sad', 'tears'], unicode: 'U+1F62D' },
  { emoji: '😡', name: 'Pouting Face', category: 'Smileys & People', keywords: ['angry', 'mad', 'rage'], unicode: 'U+1F621' },
  { emoji: '🤯', name: 'Exploding Head', category: 'Smileys & People', keywords: ['mind', 'blown', 'shock'], unicode: 'U+1F92F' },
  { emoji: '😴', name: 'Sleeping Face', category: 'Smileys & People', keywords: ['sleep', 'tired', 'zzz'], unicode: 'U+1F634' },
  { emoji: '🤩', name: 'Star-Struck', category: 'Smileys & People', keywords: ['star', 'eyes', 'amazed'], unicode: 'U+1F929' },
  { emoji: '🥳', name: 'Partying Face', category: 'Smileys & People', keywords: ['party', 'celebrate', 'birthday'], unicode: 'U+1F973' },
  { emoji: '👍', name: 'Thumbs Up', category: 'Smileys & People', keywords: ['like', 'yes', 'approve'], unicode: 'U+1F44D' },
  { emoji: '😅', name: 'Grinning Face with Sweat', category: 'Smileys & People', keywords: ['smile', 'sweat', 'relief'], unicode: 'U+1F605' },
  { emoji: '😆', name: 'Grinning Squinting Face', category: 'Smileys & People', keywords: ['smile', 'laugh', 'xd'], unicode: 'U+1F606' },
  { emoji: '🙂', name: 'Slightly Smiling Face', category: 'Smileys & People', keywords: ['smile', 'happy'], unicode: 'U+1F642' },
  { emoji: '😉', name: 'Winking Face', category: 'Smileys & People', keywords: ['wink', 'flirt'], unicode: 'U+1F609' },
  { emoji: '😇', name: 'Smiling Face with Halo', category: 'Smileys & People', keywords: ['angel', 'innocent', 'halo'], unicode: 'U+1F607' },
  { emoji: '🤗', name: 'Hugging Face', category: 'Smileys & People', keywords: ['hug', 'embrace'], unicode: 'U+1F917' },
  { emoji: '🤭', name: 'Face with Hand Over Mouth', category: 'Smileys & People', keywords: ['oops', 'shock', 'secret'], unicode: 'U+1F92D' },
  { emoji: '🤫', name: 'Shushing Face', category: 'Smileys & People', keywords: ['quiet', 'shh', 'silence'], unicode: 'U+1F92B' },
  { emoji: '🤤', name: 'Drooling Face', category: 'Smileys & People', keywords: ['drool', 'hungry'], unicode: 'U+1F924' },
  { emoji: '😋', name: 'Face Savoring Food', category: 'Smileys & People', keywords: ['yum', 'tasty', 'delicious'], unicode: 'U+1F60B' },
  { emoji: '😜', name: 'Winking Face with Tongue', category: 'Smileys & People', keywords: ['wink', 'tongue', 'playful'], unicode: 'U+1F61C' },
  { emoji: '😝', name: 'Squinting Face with Tongue', category: 'Smileys & People', keywords: ['tongue', 'playful'], unicode: 'U+1F61D' },
  { emoji: '😛', name: 'Face with Tongue', category: 'Smileys & People', keywords: ['tongue', 'playful'], unicode: 'U+1F61B' },
  { emoji: '🤑', name: 'Money-Mouth Face', category: 'Smileys & People', keywords: ['money', 'rich', 'dollar'], unicode: 'U+1F911' },
  { emoji: '🤠', name: 'Cowboy Hat Face', category: 'Smileys & People', keywords: ['cowboy', 'hat', 'west'], unicode: 'U+1F920' },
  { emoji: '😏', name: 'Smirking Face', category: 'Smileys & People', keywords: ['smirk', 'smug'], unicode: 'U+1F60F' },
  { emoji: '😒', name: 'Unamused Face', category: 'Smileys & People', keywords: ['unamused', 'annoyed'], unicode: 'U+1F612' },
  { emoji: '🙄', name: 'Face with Rolling Eyes', category: 'Smileys & People', keywords: ['roll', 'eyes', 'annoyed'], unicode: 'U+1F644' },
  { emoji: '😬', name: 'Grimacing Face', category: 'Smileys & People', keywords: ['grimace', 'awkward'], unicode: 'U+1F62C' },
  { emoji: '😔', name: 'Pensive Face', category: 'Smileys & People', keywords: ['sad', 'pensive'], unicode: 'U+1F614' },
  { emoji: '😪', name: 'Sleepy Face', category: 'Smileys & People', keywords: ['sleep', 'tired', 'sleepy'], unicode: 'U+1F62A' },
  { emoji: '🤐', name: 'Zipper-Mouth Face', category: 'Smileys & People', keywords: ['zipper', 'quiet', 'secret'], unicode: 'U+1F910' },
  { emoji: '😷', name: 'Face with Medical Mask', category: 'Smileys & People', keywords: ['mask', 'sick', 'covid'], unicode: 'U+1F637' },
  { emoji: '🤒', name: 'Face with Thermometer', category: 'Smileys & People', keywords: ['sick', 'ill', 'fever'], unicode: 'U+1F912' },
  { emoji: '🤕', name: 'Face with Head-Bandage', category: 'Smileys & People', keywords: ['injured', 'hurt', 'bandage'], unicode: 'U+1F915' },
  { emoji: '🤢', name: 'Nauseated Face', category: 'Smileys & People', keywords: ['sick', 'nausea', 'disgusted'], unicode: 'U+1F922' },
  { emoji: '🤮', name: 'Face Vomiting', category: 'Smileys & People', keywords: ['vomit', 'sick', 'puke'], unicode: 'U+1F92E' },
  { emoji: '🤧', name: 'Sneezing Face', category: 'Smileys & People', keywords: ['sneeze', 'sick', 'achoo'], unicode: 'U+1F927' },
  { emoji: '😵', name: 'Dizzy Face', category: 'Smileys & People', keywords: ['dizzy', 'confused', 'spiral'], unicode: 'U+1F635' },
  { emoji: '🤪', name: 'Zany Face', category: 'Smileys & People', keywords: ['crazy', 'wild', 'goofy'], unicode: 'U+1F92A' },
  { emoji: '😳', name: 'Flushed Face', category: 'Smileys & People', keywords: ['blush', 'embarrassed', 'shy'], unicode: 'U+1F633' },
  { emoji: '🥺', name: 'Pleading Face', category: 'Smileys & People', keywords: ['pleading', 'puppy', 'eyes'], unicode: 'U+1F97A' },
  { emoji: '😠', name: 'Angry Face', category: 'Smileys & People', keywords: ['angry', 'mad'], unicode: 'U+1F620' },
  { emoji: '😤', name: 'Face with Steam From Nose', category: 'Smileys & People', keywords: ['angry', 'frustrated', 'steam'], unicode: 'U+1F624' },
  { emoji: '😈', name: 'Smiling Face with Horns', category: 'Smileys & People', keywords: ['devil', 'evil', 'horns'], unicode: 'U+1F608' },
  { emoji: '👿', name: 'Angry Face with Horns', category: 'Smileys & People', keywords: ['devil', 'angry', 'demon'], unicode: 'U+1F47F' },
  { emoji: '💀', name: 'Skull', category: 'Smileys & People', keywords: ['skull', 'dead', 'death'], unicode: 'U+1F480' },
  { emoji: '☠️', name: 'Skull and Crossbones', category: 'Smileys & People', keywords: ['skull', 'danger', 'poison'], unicode: 'U+2620' },
  { emoji: '👻', name: 'Ghost', category: 'Smileys & People', keywords: ['ghost', 'boo', 'halloween'], unicode: 'U+1F47B' },
  { emoji: '👽', name: 'Alien', category: 'Smileys & People', keywords: ['alien', 'ufo', 'space'], unicode: 'U+1F47D' },
  { emoji: '🤖', name: 'Robot', category: 'Smileys & People', keywords: ['robot', 'bot', 'ai'], unicode: 'U+1F916' },
  { emoji: '💩', name: 'Pile of Poo', category: 'Smileys & People', keywords: ['poop', 'shit', 'crap'], unicode: 'U+1F4A9' },
  { emoji: '👋', name: 'Waving Hand', category: 'Smileys & People', keywords: ['wave', 'hello', 'goodbye'], unicode: 'U+1F44B' },
  { emoji: '🤚', name: 'Raised Back of Hand', category: 'Smileys & People', keywords: ['hand', 'raised', 'stop'], unicode: 'U+1F91A' },
  { emoji: '✋', name: 'Raised Hand', category: 'Smileys & People', keywords: ['hand', 'stop', 'raised'], unicode: 'U+270B' },
  { emoji: '🖐️', name: 'Hand with Fingers Splayed', category: 'Smileys & People', keywords: ['hand', 'fingers', 'five'], unicode: 'U+1F590' },
  { emoji: '👌', name: 'OK Hand', category: 'Smileys & People', keywords: ['ok', 'okay', 'hand'], unicode: 'U+1F44C' },
  { emoji: '✌️', name: 'Victory Hand', category: 'Smileys & People', keywords: ['peace', 'victory', 'v'], unicode: 'U+270C' },
  { emoji: '🤞', name: 'Crossed Fingers', category: 'Smileys & People', keywords: ['fingers', 'crossed', 'luck'], unicode: 'U+1F91E' },
  { emoji: '🤟', name: 'Love-You Gesture', category: 'Smileys & People', keywords: ['love', 'ily', 'hand'], unicode: 'U+1F91F' },
  { emoji: '🤘', name: 'Sign of the Horns', category: 'Smileys & People', keywords: ['rock', 'horns', 'metal'], unicode: 'U+1F918' },
  { emoji: '🤙', name: 'Call Me Hand', category: 'Smileys & People', keywords: ['call', 'phone', 'shaka'], unicode: 'U+1F919' },
  { emoji: '👈', name: 'Backhand Index Pointing Left', category: 'Smileys & People', keywords: ['point', 'left', 'finger'], unicode: 'U+1F448' },
  { emoji: '👉', name: 'Backhand Index Pointing Right', category: 'Smileys & People', keywords: ['point', 'right', 'finger'], unicode: 'U+1F449' },
  { emoji: '👆', name: 'Backhand Index Pointing Up', category: 'Smileys & People', keywords: ['point', 'up', 'finger'], unicode: 'U+1F446' },
  { emoji: '👇', name: 'Backhand Index Pointing Down', category: 'Smileys & People', keywords: ['point', 'down', 'finger'], unicode: 'U+1F447' },
  { emoji: '☝️', name: 'Index Pointing Up', category: 'Smileys & People', keywords: ['point', 'up', 'one'], unicode: 'U+261D' },
  { emoji: '👎', name: 'Thumbs Down', category: 'Smileys & People', keywords: ['dislike', 'no', 'disapprove'], unicode: 'U+1F44E' },
  { emoji: '✊', name: 'Raised Fist', category: 'Smileys & People', keywords: ['fist', 'punch', 'power'], unicode: 'U+270A' },
  { emoji: '👊', name: 'Oncoming Fist', category: 'Smileys & People', keywords: ['fist', 'punch', 'bump'], unicode: 'U+1F44A' },
  { emoji: '🤛', name: 'Left-Facing Fist', category: 'Smileys & People', keywords: ['fist', 'punch', 'left'], unicode: 'U+1F91B' },
  { emoji: '🤜', name: 'Right-Facing Fist', category: 'Smileys & People', keywords: ['fist', 'punch', 'right'], unicode: 'U+1F91C' },
  { emoji: '👏', name: 'Clapping Hands', category: 'Smileys & People', keywords: ['clap', 'applause', 'hands'], unicode: 'U+1F44F' },
  { emoji: '🙌', name: 'Raising Hands', category: 'Smileys & People', keywords: ['hands', 'celebrate', 'yay'], unicode: 'U+1F64C' },
  { emoji: '👐', name: 'Open Hands', category: 'Smileys & People', keywords: ['hands', 'open', 'hug'], unicode: 'U+1F450' },
  { emoji: '🤝', name: 'Handshake', category: 'Smileys & People', keywords: ['handshake', 'deal', 'agreement'], unicode: 'U+1F91D' },
  { emoji: '🙏', name: 'Folded Hands', category: 'Smileys & People', keywords: ['pray', 'thanks', 'please'], unicode: 'U+1F64F' },
  { emoji: '💪', name: 'Flexed Biceps', category: 'Smileys & People', keywords: ['muscle', 'strong', 'flex'], unicode: 'U+1F4AA' },
  { emoji: '🦾', name: 'Mechanical Arm', category: 'Smileys & People', keywords: ['prosthetic', 'arm', 'robot'], unicode: 'U+1F9BE' },
  { emoji: '🦿', name: 'Mechanical Leg', category: 'Smileys & People', keywords: ['prosthetic', 'leg', 'robot'], unicode: 'U+1F9BF' },
  { emoji: '🦵', name: 'Leg', category: 'Smileys & People', keywords: ['leg', 'kick'], unicode: 'U+1F9B5' },
  { emoji: '🦶', name: 'Foot', category: 'Smileys & People', keywords: ['foot', 'kick'], unicode: 'U+1F9B6' },
  { emoji: '👂', name: 'Ear', category: 'Smileys & People', keywords: ['ear', 'listen', 'hear'], unicode: 'U+1F442' },
  { emoji: '👃', name: 'Nose', category: 'Smileys & People', keywords: ['nose', 'smell'], unicode: 'U+1F443' },
  { emoji: '🧠', name: 'Brain', category: 'Smileys & People', keywords: ['brain', 'smart', 'think'], unicode: 'U+1F9E0' },
  { emoji: '👀', name: 'Eyes', category: 'Smileys & People', keywords: ['eyes', 'look', 'see'], unicode: 'U+1F440' },
  { emoji: '👁️', name: 'Eye', category: 'Smileys & People', keywords: ['eye', 'look', 'see'], unicode: 'U+1F441' },
  { emoji: '👅', name: 'Tongue', category: 'Smileys & People', keywords: ['tongue', 'taste'], unicode: 'U+1F445' },
  { emoji: '👄', name: 'Mouth', category: 'Smileys & People', keywords: ['lips', 'mouth', 'kiss'], unicode: 'U+1F444' },
  { emoji: '💋', name: 'Kiss Mark', category: 'Smileys & People', keywords: ['kiss', 'lipstick', 'lips'], unicode: 'U+1F48B' },
  { emoji: '💘', name: 'Heart with Arrow', category: 'Smileys & People', keywords: ['heart', 'love', 'cupid'], unicode: 'U+1F498' },
  { emoji: '💝', name: 'Heart with Ribbon', category: 'Smileys & People', keywords: ['heart', 'love', 'gift'], unicode: 'U+1F49D' },
  { emoji: '💖', name: 'Sparkling Heart', category: 'Smileys & People', keywords: ['heart', 'sparkle', 'love'], unicode: 'U+1F496' },
  { emoji: '💗', name: 'Growing Heart', category: 'Smileys & People', keywords: ['heart', 'love', 'growing'], unicode: 'U+1F497' },
  { emoji: '💓', name: 'Beating Heart', category: 'Smileys & People', keywords: ['heart', 'beat', 'love'], unicode: 'U+1F493' },
  { emoji: '💞', name: 'Revolving Hearts', category: 'Smileys & People', keywords: ['heart', 'love', 'revolving'], unicode: 'U+1F49E' },
  { emoji: '💕', name: 'Two Hearts', category: 'Smileys & People', keywords: ['heart', 'love', 'two'], unicode: 'U+1F495' },
  { emoji: '💟', name: 'Heart Decoration', category: 'Smileys & People', keywords: ['heart', 'love', 'decoration'], unicode: 'U+1F49F' },
  { emoji: '💔', name: 'Broken Heart', category: 'Smileys & People', keywords: ['heart', 'broken', 'sad'], unicode: 'U+1F494' },
  { emoji: '🖤', name: 'Black Heart', category: 'Smileys & People', keywords: ['heart', 'black', 'love'], unicode: 'U+1F5A4' },
  { emoji: '🤍', name: 'White Heart', category: 'Smileys & People', keywords: ['heart', 'white', 'love'], unicode: 'U+1F90D' },
  { emoji: '🤎', name: 'Brown Heart', category: 'Smileys & People', keywords: ['heart', 'brown', 'love'], unicode: 'U+1F90E' },
  { emoji: '💜', name: 'Purple Heart', category: 'Smileys & People', keywords: ['heart', 'purple', 'love'], unicode: 'U+1F49C' },
  { emoji: '💛', name: 'Yellow Heart', category: 'Smileys & People', keywords: ['heart', 'yellow', 'love'], unicode: 'U+1F49B' },
  { emoji: '🧡', name: 'Orange Heart', category: 'Smileys & People', keywords: ['heart', 'orange', 'love'], unicode: 'U+1F9E1' },

  // Animals & Nature (15 items)
  { emoji: '🐶', name: 'Dog Face', category: 'Animals & Nature', keywords: ['dog', 'pet', 'puppy'], unicode: 'U+1F436' },
  { emoji: '🐱', name: 'Cat Face', category: 'Animals & Nature', keywords: ['cat', 'pet', 'kitten'], unicode: 'U+1F431' },
  { emoji: '🐭', name: 'Mouse Face', category: 'Animals & Nature', keywords: ['mouse', 'animal'], unicode: 'U+1F42D' },
  { emoji: '🐹', name: 'Hamster', category: 'Animals & Nature', keywords: ['hamster', 'pet'], unicode: 'U+1F439' },
  { emoji: '🐰', name: 'Rabbit Face', category: 'Animals & Nature', keywords: ['rabbit', 'bunny'], unicode: 'U+1F430' },
  { emoji: '🦊', name: 'Fox', category: 'Animals & Nature', keywords: ['fox', 'animal'], unicode: 'U+1F98A' },
  { emoji: '🐻', name: 'Bear', category: 'Animals & Nature', keywords: ['bear', 'animal'], unicode: 'U+1F43B' },
  { emoji: '🐼', name: 'Panda', category: 'Animals & Nature', keywords: ['panda', 'bear'], unicode: 'U+1F43C' },
  { emoji: '🐨', name: 'Koala', category: 'Animals & Nature', keywords: ['koala', 'australia'], unicode: 'U+1F428' },
  { emoji: '🦁', name: 'Lion', category: 'Animals & Nature', keywords: ['lion', 'king'], unicode: 'U+1F981' },
  { emoji: '🐯', name: 'Tiger Face', category: 'Animals & Nature', keywords: ['tiger', 'cat'], unicode: 'U+1F42F' },
  { emoji: '🦄', name: 'Unicorn', category: 'Animals & Nature', keywords: ['unicorn', 'fantasy', 'magic'], unicode: 'U+1F984' },
  { emoji: '🌸', name: 'Cherry Blossom', category: 'Animals & Nature', keywords: ['flower', 'spring', 'pink'], unicode: 'U+1F338' },
  { emoji: '🌹', name: 'Rose', category: 'Animals & Nature', keywords: ['flower', 'rose', 'love'], unicode: 'U+1F339' },
  { emoji: '🌻', name: 'Sunflower', category: 'Animals & Nature', keywords: ['flower', 'sun', 'yellow'], unicode: 'U+1F33B' },
  { emoji: '🐮', name: 'Cow Face', category: 'Animals & Nature', keywords: ['cow', 'animal', 'farm'], unicode: 'U+1F42E' },
  { emoji: '🐷', name: 'Pig Face', category: 'Animals & Nature', keywords: ['pig', 'animal', 'farm'], unicode: 'U+1F437' },
  { emoji: '🐸', name: 'Frog', category: 'Animals & Nature', keywords: ['frog', 'animal'], unicode: 'U+1F438' },
  { emoji: '🐵', name: 'Monkey Face', category: 'Animals & Nature', keywords: ['monkey', 'animal'], unicode: 'U+1F435' },
  { emoji: '🐔', name: 'Chicken', category: 'Animals & Nature', keywords: ['chicken', 'bird', 'farm'], unicode: 'U+1F414' },
  { emoji: '🐧', name: 'Penguin', category: 'Animals & Nature', keywords: ['penguin', 'bird'], unicode: 'U+1F427' },
  { emoji: '🐦', name: 'Bird', category: 'Animals & Nature', keywords: ['bird', 'animal'], unicode: 'U+1F426' },
  { emoji: '🐤', name: 'Baby Chick', category: 'Animals & Nature', keywords: ['chick', 'baby', 'bird'], unicode: 'U+1F424' },
  { emoji: '🦅', name: 'Eagle', category: 'Animals & Nature', keywords: ['eagle', 'bird'], unicode: 'U+1F985' },
  { emoji: '🦆', name: 'Duck', category: 'Animals & Nature', keywords: ['duck', 'bird'], unicode: 'U+1F986' },
  { emoji: '🦉', name: 'Owl', category: 'Animals & Nature', keywords: ['owl', 'bird', 'wise'], unicode: 'U+1F989' },
  { emoji: '🦇', name: 'Bat', category: 'Animals & Nature', keywords: ['bat', 'animal', 'halloween'], unicode: 'U+1F987' },
  { emoji: '🐺', name: 'Wolf', category: 'Animals & Nature', keywords: ['wolf', 'animal'], unicode: 'U+1F43A' },
  { emoji: '🐗', name: 'Boar', category: 'Animals & Nature', keywords: ['boar', 'animal', 'wild'], unicode: 'U+1F417' },
  { emoji: '🐴', name: 'Horse Face', category: 'Animals & Nature', keywords: ['horse', 'animal'], unicode: 'U+1F434' },
  { emoji: '🦓', name: 'Zebra', category: 'Animals & Nature', keywords: ['zebra', 'animal'], unicode: 'U+1F993' },
  { emoji: '🦒', name: 'Giraffe', category: 'Animals & Nature', keywords: ['giraffe', 'animal'], unicode: 'U+1F992' },
  { emoji: '🦌', name: 'Deer', category: 'Animals & Nature', keywords: ['deer', 'animal'], unicode: 'U+1F98C' },
  { emoji: '🐄', name: 'Cow', category: 'Animals & Nature', keywords: ['cow', 'animal', 'farm'], unicode: 'U+1F404' },
  { emoji: '🐃', name: 'Water Buffalo', category: 'Animals & Nature', keywords: ['buffalo', 'animal'], unicode: 'U+1F403' },
  { emoji: '🐂', name: 'Ox', category: 'Animals & Nature', keywords: ['ox', 'animal'], unicode: 'U+1F402' },
  { emoji: '🐪', name: 'Camel', category: 'Animals & Nature', keywords: ['camel', 'desert'], unicode: 'U+1F42A' },
  { emoji: '🐫', name: 'Two-Hump Camel', category: 'Animals & Nature', keywords: ['camel', 'desert'], unicode: 'U+1F42B' },
  { emoji: '🦙', name: 'Llama', category: 'Animals & Nature', keywords: ['llama', 'animal'], unicode: 'U+1F999' },
  { emoji: '🦘', name: 'Kangaroo', category: 'Animals & Nature', keywords: ['kangaroo', 'australia'], unicode: 'U+1F998' },
  { emoji: '🦛', name: 'Hippopotamus', category: 'Animals & Nature', keywords: ['hippo', 'animal'], unicode: 'U+1F99B' },
  { emoji: '🦏', name: 'Rhinoceros', category: 'Animals & Nature', keywords: ['rhino', 'animal'], unicode: 'U+1F98F' },
  { emoji: '🐘', name: 'Elephant', category: 'Animals & Nature', keywords: ['elephant', 'animal'], unicode: 'U+1F418' },
  { emoji: '🐆', name: 'Leopard', category: 'Animals & Nature', keywords: ['leopard', 'animal'], unicode: 'U+1F406' },
  { emoji: '🐅', name: 'Tiger', category: 'Animals & Nature', keywords: ['tiger', 'animal'], unicode: 'U+1F405' },
  { emoji: '🦍', name: 'Gorilla', category: 'Animals & Nature', keywords: ['gorilla', 'ape'], unicode: 'U+1F98D' },
  { emoji: '🦧', name: 'Orangutan', category: 'Animals & Nature', keywords: ['orangutan', 'ape'], unicode: 'U+1F9A7' },
  { emoji: '🐒', name: 'Monkey', category: 'Animals & Nature', keywords: ['monkey', 'animal'], unicode: 'U+1F412' },
  { emoji: '🦜', name: 'Parrot', category: 'Animals & Nature', keywords: ['parrot', 'bird'], unicode: 'U+1F99C' },
  { emoji: '🦢', name: 'Swan', category: 'Animals & Nature', keywords: ['swan', 'bird'], unicode: 'U+1F9A2' },
  { emoji: '🦚', name: 'Peacock', category: 'Animals & Nature', keywords: ['peacock', 'bird'], unicode: 'U+1F99A' },
  { emoji: '🐍', name: 'Snake', category: 'Animals & Nature', keywords: ['snake', 'reptile'], unicode: 'U+1F40D' },
  { emoji: '🦎', name: 'Lizard', category: 'Animals & Nature', keywords: ['lizard', 'reptile'], unicode: 'U+1F98E' },
  { emoji: '🐢', name: 'Turtle', category: 'Animals & Nature', keywords: ['turtle', 'slow'], unicode: 'U+1F422' },
  { emoji: '🐊', name: 'Crocodile', category: 'Animals & Nature', keywords: ['crocodile', 'reptile'], unicode: 'U+1F40A' },
  { emoji: '🐙', name: 'Octopus', category: 'Animals & Nature', keywords: ['octopus', 'sea'], unicode: 'U+1F419' },
  { emoji: '🦑', name: 'Squid', category: 'Animals & Nature', keywords: ['squid', 'sea'], unicode: 'U+1F991' },
  { emoji: '🦐', name: 'Shrimp', category: 'Animals & Nature', keywords: ['shrimp', 'seafood'], unicode: 'U+1F990' },
  { emoji: '🦀', name: 'Crab', category: 'Animals & Nature', keywords: ['crab', 'seafood'], unicode: 'U+1F980' },
  { emoji: '🐡', name: 'Blowfish', category: 'Animals & Nature', keywords: ['fish', 'puffer'], unicode: 'U+1F421' },
  { emoji: '🐠', name: 'Tropical Fish', category: 'Animals & Nature', keywords: ['fish', 'tropical'], unicode: 'U+1F420' },
  { emoji: '🐟', name: 'Fish', category: 'Animals & Nature', keywords: ['fish', 'seafood'], unicode: 'U+1F41F' },
  { emoji: '🐬', name: 'Dolphin', category: 'Animals & Nature', keywords: ['dolphin', 'sea'], unicode: 'U+1F42C' },
  { emoji: '🐳', name: 'Spouting Whale', category: 'Animals & Nature', keywords: ['whale', 'sea'], unicode: 'U+1F433' },
  { emoji: '🐋', name: 'Whale', category: 'Animals & Nature', keywords: ['whale', 'sea'], unicode: 'U+1F40B' },
  { emoji: '🦈', name: 'Shark', category: 'Animals & Nature', keywords: ['shark', 'sea'], unicode: 'U+1F988' },
  { emoji: '🐌', name: 'Snail', category: 'Animals & Nature', keywords: ['snail', 'slow'], unicode: 'U+1F40C' },
  { emoji: '🦋', name: 'Butterfly', category: 'Animals & Nature', keywords: ['butterfly', 'insect'], unicode: 'U+1F98B' },
  { emoji: '🐛', name: 'Bug', category: 'Animals & Nature', keywords: ['bug', 'insect'], unicode: 'U+1F41B' },
  { emoji: '🐜', name: 'Ant', category: 'Animals & Nature', keywords: ['ant', 'insect'], unicode: 'U+1F41C' },
  { emoji: '🐝', name: 'Honeybee', category: 'Animals & Nature', keywords: ['bee', 'honey', 'insect'], unicode: 'U+1F41D' },
  { emoji: '🐞', name: 'Lady Beetle', category: 'Animals & Nature', keywords: ['ladybug', 'insect'], unicode: 'U+1F41E' },
  { emoji: '🦗', name: 'Cricket', category: 'Animals & Nature', keywords: ['cricket', 'insect'], unicode: 'U+1F997' },
  { emoji: '🕷️', name: 'Spider', category: 'Animals & Nature', keywords: ['spider', 'insect'], unicode: 'U+1F577' },
  { emoji: '🕸️', name: 'Spider Web', category: 'Animals & Nature', keywords: ['web', 'spider'], unicode: 'U+1F578' },
  { emoji: '🦂', name: 'Scorpion', category: 'Animals & Nature', keywords: ['scorpion', 'insect'], unicode: 'U+1F982' },
  { emoji: '🦟', name: 'Mosquito', category: 'Animals & Nature', keywords: ['mosquito', 'insect'], unicode: 'U+1F99F' },
  { emoji: '🦠', name: 'Microbe', category: 'Animals & Nature', keywords: ['microbe', 'germ', 'virus'], unicode: 'U+1F9A0' },
  { emoji: '💐', name: 'Bouquet', category: 'Animals & Nature', keywords: ['flowers', 'bouquet'], unicode: 'U+1F490' },
  { emoji: '🌺', name: 'Hibiscus', category: 'Animals & Nature', keywords: ['flower', 'hibiscus'], unicode: 'U+1F33A' },
  { emoji: '🌷', name: 'Tulip', category: 'Animals & Nature', keywords: ['flower', 'tulip'], unicode: 'U+1F337' },
  { emoji: '🌼', name: 'Blossom', category: 'Animals & Nature', keywords: ['flower', 'blossom'], unicode: 'U+1F33C' },
  { emoji: '🌱', name: 'Seedling', category: 'Animals & Nature', keywords: ['plant', 'seedling', 'grow'], unicode: 'U+1F331' },
  { emoji: '🌿', name: 'Herb', category: 'Animals & Nature', keywords: ['herb', 'plant', 'leaf'], unicode: 'U+1F33F' },
  { emoji: '🍀', name: 'Four Leaf Clover', category: 'Animals & Nature', keywords: ['clover', 'luck', 'four'], unicode: 'U+1F340' },
  { emoji: '🍁', name: 'Maple Leaf', category: 'Animals & Nature', keywords: ['leaf', 'maple', 'canada'], unicode: 'U+1F341' },
  { emoji: '🍂', name: 'Fallen Leaf', category: 'Animals & Nature', keywords: ['leaf', 'autumn', 'fall'], unicode: 'U+1F342' },
  { emoji: '🍃', name: 'Leaf Fluttering in Wind', category: 'Animals & Nature', keywords: ['leaf', 'wind'], unicode: 'U+1F343' },
  { emoji: '🌾', name: 'Sheaf of Rice', category: 'Animals & Nature', keywords: ['rice', 'grain', 'wheat'], unicode: 'U+1F33E' },
  { emoji: '🌵', name: 'Cactus', category: 'Animals & Nature', keywords: ['cactus', 'desert', 'plant'], unicode: 'U+1F335' },
  { emoji: '🌴', name: 'Palm Tree', category: 'Animals & Nature', keywords: ['palm', 'tree', 'tropical'], unicode: 'U+1F334' },
  { emoji: '🌳', name: 'Deciduous Tree', category: 'Animals & Nature', keywords: ['tree', 'nature'], unicode: 'U+1F333' },
  { emoji: '🌲', name: 'Evergreen Tree', category: 'Animals & Nature', keywords: ['tree', 'pine', 'evergreen'], unicode: 'U+1F332' },
  { emoji: '☘️', name: 'Shamrock', category: 'Animals & Nature', keywords: ['shamrock', 'clover', 'irish'], unicode: 'U+2618' },
  { emoji: '🌾', name: 'Rice Plant', category: 'Animals & Nature', keywords: ['rice', 'plant'], unicode: 'U+1F33E' },
  { emoji: '🌍', name: 'Globe - Europe-Africa', category: 'Animals & Nature', keywords: ['earth', 'world', 'globe'], unicode: 'U+1F30D' },
  { emoji: '🌎', name: 'Globe - Americas', category: 'Animals & Nature', keywords: ['earth', 'world', 'globe'], unicode: 'U+1F30E' },
  { emoji: '🌏', name: 'Globe - Asia-Australia', category: 'Animals & Nature', keywords: ['earth', 'world', 'globe'], unicode: 'U+1F30F' },
  { emoji: '🌙', name: 'Crescent Moon', category: 'Animals & Nature', keywords: ['moon', 'crescent', 'night'], unicode: 'U+1F319' },
  { emoji: '⭐', name: 'Star', category: 'Animals & Nature', keywords: ['star', 'favorite'], unicode: 'U+2B50' },
  { emoji: '🌟', name: 'Glowing Star', category: 'Animals & Nature', keywords: ['star', 'glow'], unicode: 'U+1F31F' },
  { emoji: '✨', name: 'Sparkles', category: 'Animals & Nature', keywords: ['sparkle', 'shine'], unicode: 'U+2728' },
  { emoji: '⚡', name: 'High Voltage', category: 'Animals & Nature', keywords: ['lightning', 'bolt', 'electric'], unicode: 'U+26A1' },
  { emoji: '☄️', name: 'Comet', category: 'Animals & Nature', keywords: ['comet', 'space'], unicode: 'U+2604' },
  { emoji: '💫', name: 'Dizzy', category: 'Animals & Nature', keywords: ['dizzy', 'star', 'sparkle'], unicode: 'U+1F4AB' },
  { emoji: '☀️', name: 'Sun', category: 'Animals & Nature', keywords: ['sun', 'sunny', 'weather'], unicode: 'U+2600' },
  { emoji: '🌤️', name: 'Sun Behind Small Cloud', category: 'Animals & Nature', keywords: ['sun', 'cloud', 'weather'], unicode: 'U+1F324' },
  { emoji: '⛅', name: 'Sun Behind Cloud', category: 'Animals & Nature', keywords: ['sun', 'cloud', 'weather'], unicode: 'U+26C5' },
  { emoji: '🌥️', name: 'Sun Behind Large Cloud', category: 'Animals & Nature', keywords: ['sun', 'cloud', 'weather'], unicode: 'U+1F325' },
  { emoji: '☁️', name: 'Cloud', category: 'Animals & Nature', keywords: ['cloud', 'weather'], unicode: 'U+2601' },
  { emoji: '🌦️', name: 'Sun Behind Rain Cloud', category: 'Animals & Nature', keywords: ['sun', 'rain', 'weather'], unicode: 'U+1F326' },
  { emoji: '🌧️', name: 'Cloud with Rain', category: 'Animals & Nature', keywords: ['rain', 'cloud', 'weather'], unicode: 'U+1F327' },
  { emoji: '⛈️', name: 'Cloud with Lightning and Rain', category: 'Animals & Nature', keywords: ['storm', 'thunder', 'weather'], unicode: 'U+26C8' },
  { emoji: '🌩️', name: 'Cloud with Lightning', category: 'Animals & Nature', keywords: ['lightning', 'cloud', 'weather'], unicode: 'U+1F329' },
  { emoji: '🌨️', name: 'Cloud with Snow', category: 'Animals & Nature', keywords: ['snow', 'cloud', 'weather'], unicode: 'U+1F328' },
  { emoji: '❄️', name: 'Snowflake', category: 'Animals & Nature', keywords: ['snow', 'cold', 'winter'], unicode: 'U+2744' },
  { emoji: '☃️', name: 'Snowman', category: 'Animals & Nature', keywords: ['snowman', 'winter', 'cold'], unicode: 'U+2603' },
  { emoji: '⛄', name: 'Snowman Without Snow', category: 'Animals & Nature', keywords: ['snowman', 'winter'], unicode: 'U+26C4' },
  { emoji: '🌬️', name: 'Wind Face', category: 'Animals & Nature', keywords: ['wind', 'blow', 'weather'], unicode: 'U+1F32C' },
  { emoji: '💨', name: 'Dashing Away', category: 'Animals & Nature', keywords: ['dash', 'wind', 'fast'], unicode: 'U+1F4A8' },
  { emoji: '🌪️', name: 'Tornado', category: 'Animals & Nature', keywords: ['tornado', 'weather'], unicode: 'U+1F32A' },
  { emoji: '🌫️', name: 'Fog', category: 'Animals & Nature', keywords: ['fog', 'weather'], unicode: 'U+1F32B' },
  { emoji: '🌈', name: 'Rainbow', category: 'Animals & Nature', keywords: ['rainbow', 'weather', 'colors'], unicode: 'U+1F308' },
  { emoji: '🔥', name: 'Fire', category: 'Animals & Nature', keywords: ['fire', 'hot', 'flame'], unicode: 'U+1F525' },
  { emoji: '💧', name: 'Droplet', category: 'Animals & Nature', keywords: ['water', 'drop', 'wet'], unicode: 'U+1F4A7' },
  { emoji: '🌊', name: 'Water Wave', category: 'Animals & Nature', keywords: ['wave', 'water', 'ocean'], unicode: 'U+1F30A' },

  // Food & Drink (15 items)
  { emoji: '🍕', name: 'Pizza', category: 'Food & Drink', keywords: ['pizza', 'food', 'italian'], unicode: 'U+1F355' },
  { emoji: '🍔', name: 'Hamburger', category: 'Food & Drink', keywords: ['burger', 'food'], unicode: 'U+1F354' },
  { emoji: '🍟', name: 'French Fries', category: 'Food & Drink', keywords: ['fries', 'food'], unicode: 'U+1F35F' },
  { emoji: '🌭', name: 'Hot Dog', category: 'Food & Drink', keywords: ['hotdog', 'food'], unicode: 'U+1F32D' },
  { emoji: '🍿', name: 'Popcorn', category: 'Food & Drink', keywords: ['popcorn', 'snack', 'movie'], unicode: 'U+1F37F' },
  { emoji: '🍩', name: 'Doughnut', category: 'Food & Drink', keywords: ['donut', 'dessert', 'sweet'], unicode: 'U+1F369' },
  { emoji: '🍪', name: 'Cookie', category: 'Food & Drink', keywords: ['cookie', 'dessert'], unicode: 'U+1F36A' },
  { emoji: '🎂', name: 'Birthday Cake', category: 'Food & Drink', keywords: ['cake', 'birthday', 'dessert'], unicode: 'U+1F382' },
  { emoji: '🍰', name: 'Shortcake', category: 'Food & Drink', keywords: ['cake', 'dessert', 'sweet'], unicode: 'U+1F370' },
  { emoji: '🍦', name: 'Soft Ice Cream', category: 'Food & Drink', keywords: ['ice cream', 'dessert', 'cone'], unicode: 'U+1F366' },
  { emoji: '🍓', name: 'Strawberry', category: 'Food & Drink', keywords: ['strawberry', 'fruit', 'berry'], unicode: 'U+1F353' },
  { emoji: '🍎', name: 'Red Apple', category: 'Food & Drink', keywords: ['apple', 'fruit', 'red'], unicode: 'U+1F34E' },
  { emoji: '🍊', name: 'Tangerine', category: 'Food & Drink', keywords: ['orange', 'fruit'], unicode: 'U+1F34A' },
  { emoji: '☕', name: 'Hot Beverage', category: 'Food & Drink', keywords: ['coffee', 'tea', 'drink'], unicode: 'U+2615' },
  { emoji: '🍷', name: 'Wine Glass', category: 'Food & Drink', keywords: ['wine', 'drink', 'alcohol'], unicode: 'U+1F377' },
  { emoji: '🍇', name: 'Grapes', category: 'Food & Drink', keywords: ['grapes', 'fruit'], unicode: 'U+1F347' },
  { emoji: '🍉', name: 'Watermelon', category: 'Food & Drink', keywords: ['watermelon', 'fruit'], unicode: 'U+1F349' },
  { emoji: '🍌', name: 'Banana', category: 'Food & Drink', keywords: ['banana', 'fruit'], unicode: 'U+1F34C' },
  { emoji: '🍍', name: 'Pineapple', category: 'Food & Drink', keywords: ['pineapple', 'fruit'], unicode: 'U+1F34D' },
  { emoji: '🥭', name: 'Mango', category: 'Food & Drink', keywords: ['mango', 'fruit'], unicode: 'U+1F96D' },
  { emoji: '🍑', name: 'Peach', category: 'Food & Drink', keywords: ['peach', 'fruit'], unicode: 'U+1F351' },
  { emoji: '🍒', name: 'Cherries', category: 'Food & Drink', keywords: ['cherry', 'fruit'], unicode: 'U+1F352' },
  { emoji: '🍈', name: 'Melon', category: 'Food & Drink', keywords: ['melon', 'fruit'], unicode: 'U+1F348' },
  { emoji: '🍋', name: 'Lemon', category: 'Food & Drink', keywords: ['lemon', 'fruit'], unicode: 'U+1F34B' },
  { emoji: '🍐', name: 'Pear', category: 'Food & Drink', keywords: ['pear', 'fruit'], unicode: 'U+1F350' },
  { emoji: '🥝', name: 'Kiwi Fruit', category: 'Food & Drink', keywords: ['kiwi', 'fruit'], unicode: 'U+1F95D' },
  { emoji: '🍅', name: 'Tomato', category: 'Food & Drink', keywords: ['tomato', 'vegetable'], unicode: 'U+1F345' },
  { emoji: '🥥', name: 'Coconut', category: 'Food & Drink', keywords: ['coconut', 'fruit'], unicode: 'U+1F965' },
  { emoji: '🥑', name: 'Avocado', category: 'Food & Drink', keywords: ['avocado', 'fruit'], unicode: 'U+1F951' },
  { emoji: '🍆', name: 'Eggplant', category: 'Food & Drink', keywords: ['eggplant', 'vegetable'], unicode: 'U+1F346' },
  { emoji: '🥔', name: 'Potato', category: 'Food & Drink', keywords: ['potato', 'vegetable'], unicode: 'U+1F954' },
  { emoji: '🥕', name: 'Carrot', category: 'Food & Drink', keywords: ['carrot', 'vegetable'], unicode: 'U+1F955' },
  { emoji: '🌽', name: 'Corn', category: 'Food & Drink', keywords: ['corn', 'vegetable'], unicode: 'U+1F33D' },
  { emoji: '🌶️', name: 'Hot Pepper', category: 'Food & Drink', keywords: ['pepper', 'hot', 'spicy'], unicode: 'U+1F336' },
  { emoji: '🥒', name: 'Cucumber', category: 'Food & Drink', keywords: ['cucumber', 'vegetable'], unicode: 'U+1F952' },
  { emoji: '🥬', name: 'Leafy Green', category: 'Food & Drink', keywords: ['lettuce', 'vegetable', 'salad'], unicode: 'U+1F96C' },
  { emoji: '🥦', name: 'Broccoli', category: 'Food & Drink', keywords: ['broccoli', 'vegetable'], unicode: 'U+1F966' },
  { emoji: '🧄', name: 'Garlic', category: 'Food & Drink', keywords: ['garlic', 'vegetable'], unicode: 'U+1F9C4' },
  { emoji: '🧅', name: 'Onion', category: 'Food & Drink', keywords: ['onion', 'vegetable'], unicode: 'U+1F9C5' },
  { emoji: '🍄', name: 'Mushroom', category: 'Food & Drink', keywords: ['mushroom', 'vegetable'], unicode: 'U+1F344' },
  { emoji: '🥜', name: 'Peanuts', category: 'Food & Drink', keywords: ['peanuts', 'nuts'], unicode: 'U+1F95C' },
  { emoji: '🌰', name: 'Chestnut', category: 'Food & Drink', keywords: ['chestnut', 'nut'], unicode: 'U+1F330' },
  { emoji: '🍞', name: 'Bread', category: 'Food & Drink', keywords: ['bread', 'food'], unicode: 'U+1F35E' },
  { emoji: '🥐', name: 'Croissant', category: 'Food & Drink', keywords: ['croissant', 'bread'], unicode: 'U+1F950' },
  { emoji: '🥖', name: 'Baguette Bread', category: 'Food & Drink', keywords: ['baguette', 'bread', 'french'], unicode: 'U+1F956' },
  { emoji: '🥨', name: 'Pretzel', category: 'Food & Drink', keywords: ['pretzel', 'snack'], unicode: 'U+1F968' },
  { emoji: '🥯', name: 'Bagel', category: 'Food & Drink', keywords: ['bagel', 'bread'], unicode: 'U+1F96F' },
  { emoji: '🥞', name: 'Pancakes', category: 'Food & Drink', keywords: ['pancakes', 'breakfast'], unicode: 'U+1F95E' },
  { emoji: '🧇', name: 'Waffle', category: 'Food & Drink', keywords: ['waffle', 'breakfast'], unicode: 'U+1F9C7' },
  { emoji: '🧀', name: 'Cheese Wedge', category: 'Food & Drink', keywords: ['cheese', 'food'], unicode: 'U+1F9C0' },
  { emoji: '🍖', name: 'Meat on Bone', category: 'Food & Drink', keywords: ['meat', 'food'], unicode: 'U+1F356' },
  { emoji: '🍗', name: 'Poultry Leg', category: 'Food & Drink', keywords: ['chicken', 'food'], unicode: 'U+1F357' },
  { emoji: '🥩', name: 'Cut of Meat', category: 'Food & Drink', keywords: ['meat', 'steak'], unicode: 'U+1F969' },
  { emoji: '🥓', name: 'Bacon', category: 'Food & Drink', keywords: ['bacon', 'meat'], unicode: 'U+1F953' },
  { emoji: '🌮', name: 'Taco', category: 'Food & Drink', keywords: ['taco', 'mexican', 'food'], unicode: 'U+1F32E' },
  { emoji: '🌯', name: 'Burrito', category: 'Food & Drink', keywords: ['burrito', 'mexican', 'food'], unicode: 'U+1F32F' },
  { emoji: '🥙', name: 'Stuffed Flatbread', category: 'Food & Drink', keywords: ['pita', 'kebab', 'food'], unicode: 'U+1F959' },
  { emoji: '🥚', name: 'Egg', category: 'Food & Drink', keywords: ['egg', 'food'], unicode: 'U+1F95A' },
  { emoji: '🍳', name: 'Cooking', category: 'Food & Drink', keywords: ['cooking', 'egg', 'frying'], unicode: 'U+1F373' },
  { emoji: '🥘', name: 'Shallow Pan of Food', category: 'Food & Drink', keywords: ['paella', 'food'], unicode: 'U+1F958' },
  { emoji: '🍲', name: 'Pot of Food', category: 'Food & Drink', keywords: ['pot', 'stew', 'food'], unicode: 'U+1F372' },
  { emoji: '🥣', name: 'Bowl with Spoon', category: 'Food & Drink', keywords: ['bowl', 'cereal', 'food'], unicode: 'U+1F963' },
  { emoji: '🥗', name: 'Green Salad', category: 'Food & Drink', keywords: ['salad', 'healthy', 'food'], unicode: 'U+1F957' },
  { emoji: '🍝', name: 'Spaghetti', category: 'Food & Drink', keywords: ['spaghetti', 'pasta', 'italian'], unicode: 'U+1F35D' },
  { emoji: '🍜', name: 'Steaming Bowl', category: 'Food & Drink', keywords: ['ramen', 'noodles', 'food'], unicode: 'U+1F35C' },
  { emoji: '🍱', name: 'Bento Box', category: 'Food & Drink', keywords: ['bento', 'japanese', 'food'], unicode: 'U+1F371' },
  { emoji: '🍛', name: 'Curry Rice', category: 'Food & Drink', keywords: ['curry', 'rice', 'food'], unicode: 'U+1F35B' },
  { emoji: '🍙', name: 'Rice Ball', category: 'Food & Drink', keywords: ['onigiri', 'rice', 'japanese'], unicode: 'U+1F359' },
  { emoji: '🍚', name: 'Cooked Rice', category: 'Food & Drink', keywords: ['rice', 'food'], unicode: 'U+1F35A' },
  { emoji: '🍘', name: 'Rice Cracker', category: 'Food & Drink', keywords: ['rice cracker', 'snack'], unicode: 'U+1F358' },
  { emoji: '🍢', name: 'Oden', category: 'Food & Drink', keywords: ['oden', 'japanese', 'food'], unicode: 'U+1F362' },
  { emoji: '🍣', name: 'Sushi', category: 'Food & Drink', keywords: ['sushi', 'japanese', 'food'], unicode: 'U+1F363' },
  { emoji: '🍤', name: 'Fried Shrimp', category: 'Food & Drink', keywords: ['shrimp', 'tempura', 'food'], unicode: 'U+1F364' },
  { emoji: '🍥', name: 'Fish Cake with Swirl', category: 'Food & Drink', keywords: ['fish cake', 'japanese'], unicode: 'U+1F365' },
  { emoji: '🥮', name: 'Moon Cake', category: 'Food & Drink', keywords: ['moon cake', 'chinese', 'dessert'], unicode: 'U+1F96E' },
  { emoji: '🍡', name: 'Dango', category: 'Food & Drink', keywords: ['dango', 'japanese', 'dessert'], unicode: 'U+1F361' },
  { emoji: '🥟', name: 'Dumpling', category: 'Food & Drink', keywords: ['dumpling', 'food'], unicode: 'U+1F95F' },
  { emoji: '🥠', name: 'Fortune Cookie', category: 'Food & Drink', keywords: ['fortune cookie', 'chinese'], unicode: 'U+1F960' },
  { emoji: '🥡', name: 'Takeout Box', category: 'Food & Drink', keywords: ['takeout', 'chinese', 'food'], unicode: 'U+1F961' },
  { emoji: '🍧', name: 'Shaved Ice', category: 'Food & Drink', keywords: ['shaved ice', 'dessert'], unicode: 'U+1F367' },
  { emoji: '🍨', name: 'Ice Cream', category: 'Food & Drink', keywords: ['ice cream', 'dessert'], unicode: 'U+1F368' },
  { emoji: '🍬', name: 'Candy', category: 'Food & Drink', keywords: ['candy', 'sweet'], unicode: 'U+1F36C' },
  { emoji: '🍭', name: 'Lollipop', category: 'Food & Drink', keywords: ['lollipop', 'candy', 'sweet'], unicode: 'U+1F36D' },
  { emoji: '🍮', name: 'Custard', category: 'Food & Drink', keywords: ['custard', 'pudding', 'dessert'], unicode: 'U+1F36E' },
  { emoji: '🍯', name: 'Honey Pot', category: 'Food & Drink', keywords: ['honey', 'sweet'], unicode: 'U+1F36F' },
  { emoji: '🍼', name: 'Baby Bottle', category: 'Food & Drink', keywords: ['baby', 'bottle', 'milk'], unicode: 'U+1F37C' },
  { emoji: '🥛', name: 'Glass of Milk', category: 'Food & Drink', keywords: ['milk', 'drink'], unicode: 'U+1F95B' },
  { emoji: '🍵', name: 'Teacup Without Handle', category: 'Food & Drink', keywords: ['tea', 'green tea', 'drink'], unicode: 'U+1F375' },
  { emoji: '🍶', name: 'Sake', category: 'Food & Drink', keywords: ['sake', 'japanese', 'drink'], unicode: 'U+1F376' },
  { emoji: '🍾', name: 'Bottle with Popping Cork', category: 'Food & Drink', keywords: ['champagne', 'celebration', 'drink'], unicode: 'U+1F37E' },
  { emoji: '🍸', name: 'Cocktail Glass', category: 'Food & Drink', keywords: ['cocktail', 'drink', 'martini'], unicode: 'U+1F378' },
  { emoji: '🍹', name: 'Tropical Drink', category: 'Food & Drink', keywords: ['tropical', 'drink', 'cocktail'], unicode: 'U+1F379' },
  { emoji: '🍺', name: 'Beer Mug', category: 'Food & Drink', keywords: ['beer', 'drink'], unicode: 'U+1F37A' },
  { emoji: '🍻', name: 'Clinking Beer Mugs', category: 'Food & Drink', keywords: ['beer', 'cheers', 'drink'], unicode: 'U+1F37B' },
  { emoji: '🥂', name: 'Clinking Glasses', category: 'Food & Drink', keywords: ['cheers', 'toast', 'glasses'], unicode: 'U+1F942' },
  { emoji: '🥃', name: 'Tumbler Glass', category: 'Food & Drink', keywords: ['whiskey', 'glass', 'drink'], unicode: 'U+1F943' },
  { emoji: '🥤', name: 'Cup with Straw', category: 'Food & Drink', keywords: ['cup', 'drink', 'soda'], unicode: 'U+1F964' },
  { emoji: '🧃', name: 'Beverage Box', category: 'Food & Drink', keywords: ['juice', 'box', 'drink'], unicode: 'U+1F9C3' },
  { emoji: '🧉', name: 'Mate', category: 'Food & Drink', keywords: ['mate', 'drink'], unicode: 'U+1F9C9' },
  { emoji: '🧊', name: 'Ice', category: 'Food & Drink', keywords: ['ice', 'cube', 'cold'], unicode: 'U+1F9CA' },
  { emoji: '🥢', name: 'Chopsticks', category: 'Food & Drink', keywords: ['chopsticks', 'utensils'], unicode: 'U+1F962' },
  { emoji: '🍴', name: 'Fork and Knife', category: 'Food & Drink', keywords: ['fork', 'knife', 'utensils'], unicode: 'U+1F374' },
  { emoji: '🥄', name: 'Spoon', category: 'Food & Drink', keywords: ['spoon', 'utensil'], unicode: 'U+1F944' },
  { emoji: '🔪', name: 'Kitchen Knife', category: 'Food & Drink', keywords: ['knife', 'cooking'], unicode: 'U+1F52A' },
  { emoji: '🏺', name: 'Amphora', category: 'Food & Drink', keywords: ['amphora', 'jar'], unicode: 'U+1F3FA' },

  // Travel & Places (12 items)
  { emoji: '✈️', name: 'Airplane', category: 'Travel & Places', keywords: ['airplane', 'travel', 'flight'], unicode: 'U+2708' },
  { emoji: '🚗', name: 'Automobile', category: 'Travel & Places', keywords: ['car', 'vehicle', 'drive'], unicode: 'U+1F697' },
  { emoji: '🚕', name: 'Taxi', category: 'Travel & Places', keywords: ['taxi', 'cab', 'car'], unicode: 'U+1F695' },
  { emoji: '🚙', name: 'Sport Utility Vehicle', category: 'Travel & Places', keywords: ['suv', 'car', 'vehicle'], unicode: 'U+1F699' },
  { emoji: '🚌', name: 'Bus', category: 'Travel & Places', keywords: ['bus', 'vehicle'], unicode: 'U+1F68C' },
  { emoji: '🚲', name: 'Bicycle', category: 'Travel & Places', keywords: ['bike', 'bicycle', 'cycle'], unicode: 'U+1F6B2' },
  { emoji: '🏠', name: 'House', category: 'Travel & Places', keywords: ['house', 'home'], unicode: 'U+1F3E0' },
  { emoji: '🏢', name: 'Office Building', category: 'Travel & Places', keywords: ['office', 'building', 'work'], unicode: 'U+1F3E2' },
  { emoji: '🏨', name: 'Hotel', category: 'Travel & Places', keywords: ['hotel', 'building'], unicode: 'U+1F3E8' },
  { emoji: '🌍', name: 'Globe Showing Europe-Africa', category: 'Travel & Places', keywords: ['earth', 'world', 'globe'], unicode: 'U+1F30D' },
  { emoji: '🗺️', name: 'World Map', category: 'Travel & Places', keywords: ['map', 'world', 'travel'], unicode: 'U+1F5FA' },
  { emoji: '⛰️', name: 'Mountain', category: 'Travel & Places', keywords: ['mountain', 'nature'], unicode: 'U+26F0' },

  // Activities (10 items)
  { emoji: '⚽', name: 'Soccer Ball', category: 'Activities', keywords: ['soccer', 'football', 'sport'], unicode: 'U+26BD' },
  { emoji: '🏀', name: 'Basketball', category: 'Activities', keywords: ['basketball', 'sport'], unicode: 'U+1F3C0' },
  { emoji: '🏈', name: 'American Football', category: 'Activities', keywords: ['football', 'sport'], unicode: 'U+1F3C8' },
  { emoji: '⚾', name: 'Baseball', category: 'Activities', keywords: ['baseball', 'sport'], unicode: 'U+26BE' },
  { emoji: '🎮', name: 'Video Game', category: 'Activities', keywords: ['game', 'video', 'controller'], unicode: 'U+1F3AE' },
  { emoji: '🎯', name: 'Direct Hit', category: 'Activities', keywords: ['target', 'bullseye', 'dart'], unicode: 'U+1F3AF' },
  { emoji: '🎨', name: 'Artist Palette', category: 'Activities', keywords: ['art', 'paint', 'creative'], unicode: 'U+1F3A8' },
  { emoji: '🎭', name: 'Performing Arts', category: 'Activities', keywords: ['theater', 'drama', 'mask'], unicode: 'U+1F3AD' },
  { emoji: '🎪', name: 'Circus Tent', category: 'Activities', keywords: ['circus', 'tent', 'entertainment'], unicode: 'U+1F3AA' },
  { emoji: '🎬', name: 'Clapper Board', category: 'Activities', keywords: ['movie', 'film', 'cinema'], unicode: 'U+1F3AC' },

  // Objects (13 items)
  { emoji: '💻', name: 'Laptop', category: 'Objects', keywords: ['laptop', 'computer', 'technology'], unicode: 'U+1F4BB' },
  { emoji: '📱', name: 'Mobile Phone', category: 'Objects', keywords: ['phone', 'mobile', 'smartphone'], unicode: 'U+1F4F1' },
  { emoji: '⌚', name: 'Watch', category: 'Objects', keywords: ['watch', 'time', 'clock'], unicode: 'U+231A' },
  { emoji: '📷', name: 'Camera', category: 'Objects', keywords: ['camera', 'photo', 'picture'], unicode: 'U+1F4F7' },
  { emoji: '💡', name: 'Light Bulb', category: 'Objects', keywords: ['idea', 'light', 'bulb'], unicode: 'U+1F4A1' },
  { emoji: '📚', name: 'Books', category: 'Objects', keywords: ['books', 'read', 'library'], unicode: 'U+1F4DA' },
  { emoji: '✉️', name: 'Envelope', category: 'Objects', keywords: ['email', 'mail', 'message'], unicode: 'U+2709' },
  { emoji: '📝', name: 'Memo', category: 'Objects', keywords: ['note', 'write', 'document'], unicode: 'U+1F4DD' },
  { emoji: '🎁', name: 'Wrapped Gift', category: 'Objects', keywords: ['gift', 'present', 'birthday'], unicode: 'U+1F381' },
  { emoji: '🔑', name: 'Key', category: 'Objects', keywords: ['key', 'lock', 'security'], unicode: 'U+1F511' },
  { emoji: '🔨', name: 'Hammer', category: 'Objects', keywords: ['hammer', 'tool', 'fix'], unicode: 'U+1F528' },
  { emoji: '💰', name: 'Money Bag', category: 'Objects', keywords: ['money', 'cash', 'wealth'], unicode: 'U+1F4B0' },
  { emoji: '💎', name: 'Gem Stone', category: 'Objects', keywords: ['gem', 'diamond', 'jewel'], unicode: 'U+1F48E' },

  // Symbols (10 items)
  { emoji: '❤️', name: 'Red Heart', category: 'Symbols', keywords: ['heart', 'love', 'red'], unicode: 'U+2764' },
  { emoji: '💙', name: 'Blue Heart', category: 'Symbols', keywords: ['heart', 'blue', 'love'], unicode: 'U+1F499' },
  { emoji: '💚', name: 'Green Heart', category: 'Symbols', keywords: ['heart', 'green', 'love'], unicode: 'U+1F49A' },
  { emoji: '⭐', name: 'Star', category: 'Symbols', keywords: ['star', 'favorite'], unicode: 'U+2B50' },
  { emoji: '✨', name: 'Sparkles', category: 'Symbols', keywords: ['sparkle', 'shine', 'star'], unicode: 'U+2728' },
  { emoji: '🔥', name: 'Fire', category: 'Symbols', keywords: ['fire', 'hot', 'flame'], unicode: 'U+1F525' },
  { emoji: '💯', name: 'Hundred Points', category: 'Symbols', keywords: ['hundred', '100', 'perfect'], unicode: 'U+1F4AF' },
  { emoji: '✅', name: 'Check Mark Button', category: 'Symbols', keywords: ['check', 'yes', 'done'], unicode: 'U+2705' },
  { emoji: '❌', name: 'Cross Mark', category: 'Symbols', keywords: ['x', 'no', 'wrong'], unicode: 'U+274C' },
  { emoji: '⚠️', name: 'Warning', category: 'Symbols', keywords: ['warning', 'caution', 'alert'], unicode: 'U+26A0' },

  // Flags (5 items)
  { emoji: '🏳️', name: 'White Flag', category: 'Flags', keywords: ['flag', 'white'], unicode: 'U+1F3F3' },
  { emoji: '🏴', name: 'Black Flag', category: 'Flags', keywords: ['flag', 'black'], unicode: 'U+1F3F4' },
  { emoji: '🏁', name: 'Chequered Flag', category: 'Flags', keywords: ['flag', 'racing', 'finish'], unicode: 'U+1F3C1' },
  { emoji: '🚩', name: 'Triangular Flag', category: 'Flags', keywords: ['flag', 'red'], unicode: 'U+1F6A9' },
  { emoji: '🏴‍☠️', name: 'Pirate Flag', category: 'Flags', keywords: ['flag', 'pirate', 'skull'], unicode: 'U+1F3F4-200D-2620-FE0F' },
];

export function searchEmojis(query: string, category: EmojiCategory = 'All'): Emoji[] {
  const lowerQuery = query.toLowerCase().trim();

  let filtered = category === 'All' ? emojis : emojis.filter(e => e.category === category);

  if (lowerQuery) {
    filtered = filtered.filter(e => e.name.toLowerCase().includes(lowerQuery) || e.keywords.some(k => k.toLowerCase().includes(lowerQuery)) || e.emoji.includes(lowerQuery));
  }

  return filtered;
}

export function getEmojisByCategory(category: EmojiCategory): Emoji[] {
  if (category === 'All') return emojis;
  return emojis.filter(e => e.category === category);
}
