export interface Symbol {
  symbol: string;
  name: string;
  category: string;
  unicode: string;
  keywords: string[];
}

export const symbolCategories = ['All', 'Mathematics', 'Arrows', 'Currency', 'Punctuation', 'Shapes', 'Greek Letters', 'Technical', 'Miscellaneous'] as const;

export type SymbolCategory = (typeof symbolCategories)[number];

export const symbols: Symbol[] = [
  // Mathematics (20 symbols)
  { symbol: '+', name: 'Plus Sign', category: 'Mathematics', unicode: 'U+002B', keywords: ['plus', 'add', 'positive'] },
  { symbol: '−', name: 'Minus Sign', category: 'Mathematics', unicode: 'U+2212', keywords: ['minus', 'subtract', 'negative'] },
  { symbol: '×', name: 'Multiplication Sign', category: 'Mathematics', unicode: 'U+00D7', keywords: ['multiply', 'times', 'cross'] },
  { symbol: '÷', name: 'Division Sign', category: 'Mathematics', unicode: 'U+00F7', keywords: ['divide', 'division'] },
  { symbol: '=', name: 'Equals Sign', category: 'Mathematics', unicode: 'U+003D', keywords: ['equals', 'equal'] },
  { symbol: '≠', name: 'Not Equal To', category: 'Mathematics', unicode: 'U+2260', keywords: ['not equal', 'unequal'] },
  { symbol: '<', name: 'Less Than', category: 'Mathematics', unicode: 'U+003C', keywords: ['less', 'smaller'] },
  { symbol: '>', name: 'Greater Than', category: 'Mathematics', unicode: 'U+003E', keywords: ['greater', 'larger'] },
  { symbol: '≤', name: 'Less Than or Equal To', category: 'Mathematics', unicode: 'U+2264', keywords: ['less', 'equal'] },
  { symbol: '≥', name: 'Greater Than or Equal To', category: 'Mathematics', unicode: 'U+2265', keywords: ['greater', 'equal'] },
  { symbol: '±', name: 'Plus-Minus Sign', category: 'Mathematics', unicode: 'U+00B1', keywords: ['plus', 'minus', 'tolerance'] },
  { symbol: '∞', name: 'Infinity', category: 'Mathematics', unicode: 'U+221E', keywords: ['infinity', 'unlimited'] },
  { symbol: '√', name: 'Square Root', category: 'Mathematics', unicode: 'U+221A', keywords: ['root', 'radical'] },
  { symbol: '∑', name: 'Summation', category: 'Mathematics', unicode: 'U+2211', keywords: ['sum', 'total', 'sigma'] },
  { symbol: '∫', name: 'Integral', category: 'Mathematics', unicode: 'U+222B', keywords: ['integral', 'calculus'] },
  { symbol: '∂', name: 'Partial Differential', category: 'Mathematics', unicode: 'U+2202', keywords: ['partial', 'derivative'] },
  { symbol: 'π', name: 'Pi', category: 'Mathematics', unicode: 'U+03C0', keywords: ['pi', 'circle'] },
  { symbol: '°', name: 'Degree Sign', category: 'Mathematics', unicode: 'U+00B0', keywords: ['degree', 'temperature', 'angle'] },
  { symbol: '%', name: 'Percent Sign', category: 'Mathematics', unicode: 'U+0025', keywords: ['percent', 'percentage'] },
  { symbol: '‰', name: 'Per Mille Sign', category: 'Mathematics', unicode: 'U+2030', keywords: ['per mille', 'permille'] },
  { symbol: '∝', name: 'Proportional To', category: 'Mathematics', unicode: 'U+221D', keywords: ['proportional', 'ratio'] },
  { symbol: '∀', name: 'For All', category: 'Mathematics', unicode: 'U+2200', keywords: ['for all', 'universal'] },
  { symbol: '∃', name: 'There Exists', category: 'Mathematics', unicode: 'U+2203', keywords: ['exists', 'existential'] },
  { symbol: '∄', name: 'There Does Not Exist', category: 'Mathematics', unicode: 'U+2204', keywords: ['not exist'] },
  { symbol: '∅', name: 'Empty Set', category: 'Mathematics', unicode: 'U+2205', keywords: ['empty', 'null', 'set'] },
  { symbol: '∈', name: 'Element Of', category: 'Mathematics', unicode: 'U+2208', keywords: ['element', 'member', 'in'] },
  { symbol: '∉', name: 'Not An Element Of', category: 'Mathematics', unicode: 'U+2209', keywords: ['not element', 'not in'] },
  { symbol: '∩', name: 'Intersection', category: 'Mathematics', unicode: 'U+2229', keywords: ['intersection', 'and'] },
  { symbol: '∪', name: 'Union', category: 'Mathematics', unicode: 'U+222A', keywords: ['union', 'or'] },
  { symbol: '⊂', name: 'Subset Of', category: 'Mathematics', unicode: 'U+2282', keywords: ['subset', 'contained'] },
  { symbol: '⊃', name: 'Superset Of', category: 'Mathematics', unicode: 'U+2283', keywords: ['superset', 'contains'] },
  { symbol: '⊆', name: 'Subset Of Or Equal To', category: 'Mathematics', unicode: 'U+2286', keywords: ['subset', 'equal'] },
  { symbol: '⊇', name: 'Superset Of Or Equal To', category: 'Mathematics', unicode: 'U+2287', keywords: ['superset', 'equal'] },
  { symbol: '∧', name: 'Logical And', category: 'Mathematics', unicode: 'U+2227', keywords: ['and', 'logical'] },
  { symbol: '∨', name: 'Logical Or', category: 'Mathematics', unicode: 'U+2228', keywords: ['or', 'logical'] },
  { symbol: '¬', name: 'Not Sign', category: 'Mathematics', unicode: 'U+00AC', keywords: ['not', 'negation'] },
  { symbol: '∴', name: 'Therefore', category: 'Mathematics', unicode: 'U+2234', keywords: ['therefore', 'conclusion'] },
  { symbol: '∵', name: 'Because', category: 'Mathematics', unicode: 'U+2235', keywords: ['because', 'since'] },
  { symbol: '≈', name: 'Almost Equal To', category: 'Mathematics', unicode: 'U+2248', keywords: ['almost', 'approximately'] },
  { symbol: '≡', name: 'Identical To', category: 'Mathematics', unicode: 'U+2261', keywords: ['identical', 'equivalent'] },
  { symbol: '≢', name: 'Not Identical To', category: 'Mathematics', unicode: 'U+2262', keywords: ['not identical'] },
  { symbol: '≪', name: 'Much Less Than', category: 'Mathematics', unicode: 'U+226A', keywords: ['much less'] },
  { symbol: '≫', name: 'Much Greater Than', category: 'Mathematics', unicode: 'U+226B', keywords: ['much greater'] },
  { symbol: '∼', name: 'Tilde Operator', category: 'Mathematics', unicode: 'U+223C', keywords: ['tilde', 'similar'] },
  { symbol: '≅', name: 'Approximately Equal To', category: 'Mathematics', unicode: 'U+2245', keywords: ['approximately', 'congruent'] },
  { symbol: '⊕', name: 'Circled Plus', category: 'Mathematics', unicode: 'U+2295', keywords: ['circled plus', 'xor'] },
  { symbol: '⊗', name: 'Circled Times', category: 'Mathematics', unicode: 'U+2297', keywords: ['circled times', 'tensor'] },
  { symbol: '⊥', name: 'Perpendicular', category: 'Mathematics', unicode: 'U+22A5', keywords: ['perpendicular', 'orthogonal'] },
  { symbol: '∥', name: 'Parallel To', category: 'Mathematics', unicode: 'U+2225', keywords: ['parallel'] },
  { symbol: '∦', name: 'Not Parallel To', category: 'Mathematics', unicode: 'U+2226', keywords: ['not parallel'] },
  { symbol: '∠', name: 'Angle', category: 'Mathematics', unicode: 'U+2220', keywords: ['angle'] },
  { symbol: '∡', name: 'Measured Angle', category: 'Mathematics', unicode: 'U+2221', keywords: ['measured angle'] },
  { symbol: '′', name: 'Prime', category: 'Mathematics', unicode: 'U+2032', keywords: ['prime', 'derivative', 'minutes'] },
  { symbol: '″', name: 'Double Prime', category: 'Mathematics', unicode: 'U+2033', keywords: ['double prime', 'seconds'] },
  { symbol: '∇', name: 'Nabla', category: 'Mathematics', unicode: 'U+2207', keywords: ['nabla', 'gradient', 'del'] },
  { symbol: '∞', name: 'Infinity', category: 'Mathematics', unicode: 'U+221E', keywords: ['infinity', 'unlimited'] },
  { symbol: 'ℵ', name: 'Aleph', category: 'Mathematics', unicode: 'U+2135', keywords: ['aleph', 'infinite'] },
  { symbol: 'ℓ', name: 'Script Small L', category: 'Mathematics', unicode: 'U+2113', keywords: ['liter', 'length'] },
  { symbol: 'ℕ', name: 'Natural Numbers', category: 'Mathematics', unicode: 'U+2115', keywords: ['natural', 'numbers'] },
  { symbol: 'ℚ', name: 'Rational Numbers', category: 'Mathematics', unicode: 'U+211A', keywords: ['rational', 'numbers'] },
  { symbol: 'ℝ', name: 'Real Numbers', category: 'Mathematics', unicode: 'U+211D', keywords: ['real', 'numbers'] },
  { symbol: 'ℂ', name: 'Complex Numbers', category: 'Mathematics', unicode: 'U+2102', keywords: ['complex', 'numbers'] },
  { symbol: 'ℤ', name: 'Integers', category: 'Mathematics', unicode: 'U+2124', keywords: ['integers', 'numbers'] },

  // Arrows (20 symbols)
  { symbol: '←', name: 'Leftwards Arrow', category: 'Arrows', unicode: 'U+2190', keywords: ['arrow', 'left', 'back'] },
  { symbol: '→', name: 'Rightwards Arrow', category: 'Arrows', unicode: 'U+2192', keywords: ['arrow', 'right', 'forward'] },
  { symbol: '↑', name: 'Upwards Arrow', category: 'Arrows', unicode: 'U+2191', keywords: ['arrow', 'up'] },
  { symbol: '↓', name: 'Downwards Arrow', category: 'Arrows', unicode: 'U+2193', keywords: ['arrow', 'down'] },
  { symbol: '↔', name: 'Left Right Arrow', category: 'Arrows', unicode: 'U+2194', keywords: ['arrow', 'horizontal', 'both'] },
  { symbol: '↕', name: 'Up Down Arrow', category: 'Arrows', unicode: 'U+2195', keywords: ['arrow', 'vertical', 'both'] },
  { symbol: '⇐', name: 'Leftwards Double Arrow', category: 'Arrows', unicode: 'U+21D0', keywords: ['arrow', 'left', 'double'] },
  { symbol: '⇒', name: 'Rightwards Double Arrow', category: 'Arrows', unicode: 'U+21D2', keywords: ['arrow', 'right', 'double'] },
  { symbol: '⇑', name: 'Upwards Double Arrow', category: 'Arrows', unicode: 'U+21D1', keywords: ['arrow', 'up', 'double'] },
  { symbol: '⇓', name: 'Downwards Double Arrow', category: 'Arrows', unicode: 'U+21D3', keywords: ['arrow', 'down', 'double'] },
  { symbol: '↖', name: 'North West Arrow', category: 'Arrows', unicode: 'U+2196', keywords: ['arrow', 'diagonal', 'upleft'] },
  { symbol: '↗', name: 'North East Arrow', category: 'Arrows', unicode: 'U+2197', keywords: ['arrow', 'diagonal', 'upright'] },
  { symbol: '↘', name: 'South East Arrow', category: 'Arrows', unicode: 'U+2198', keywords: ['arrow', 'diagonal', 'downright'] },
  { symbol: '↙', name: 'South West Arrow', category: 'Arrows', unicode: 'U+2199', keywords: ['arrow', 'diagonal', 'downleft'] },
  { symbol: '⟵', name: 'Long Leftwards Arrow', category: 'Arrows', unicode: 'U+27F5', keywords: ['arrow', 'left', 'long'] },
  { symbol: '⟶', name: 'Long Rightwards Arrow', category: 'Arrows', unicode: 'U+27F6', keywords: ['arrow', 'right', 'long'] },
  { symbol: '↩', name: 'Leftwards Arrow with Hook', category: 'Arrows', unicode: 'U+21A9', keywords: ['arrow', 'return', 'hook'] },
  { symbol: '↪', name: 'Rightwards Arrow with Hook', category: 'Arrows', unicode: 'U+21AA', keywords: ['arrow', 'enter', 'hook'] },
  { symbol: '↺', name: 'Anticlockwise Open Circle Arrow', category: 'Arrows', unicode: 'U+21BA', keywords: ['arrow', 'rotate', 'refresh'] },
  { symbol: '↻', name: 'Clockwise Open Circle Arrow', category: 'Arrows', unicode: 'U+21BB', keywords: ['arrow', 'rotate', 'refresh'] },

  // Currency (15 symbols)
  { symbol: '$', name: 'Dollar Sign', category: 'Currency', unicode: 'U+0024', keywords: ['dollar', 'usd', 'money'] },
  { symbol: '€', name: 'Euro Sign', category: 'Currency', unicode: 'U+20AC', keywords: ['euro', 'eur', 'money'] },
  { symbol: '£', name: 'Pound Sign', category: 'Currency', unicode: 'U+00A3', keywords: ['pound', 'gbp', 'money'] },
  { symbol: '¥', name: 'Yen Sign', category: 'Currency', unicode: 'U+00A5', keywords: ['yen', 'jpy', 'money'] },
  { symbol: '₹', name: 'Indian Rupee Sign', category: 'Currency', unicode: 'U+20B9', keywords: ['rupee', 'inr', 'money'] },
  { symbol: '₽', name: 'Ruble Sign', category: 'Currency', unicode: 'U+20BD', keywords: ['ruble', 'rub', 'money'] },
  { symbol: '₿', name: 'Bitcoin Sign', category: 'Currency', unicode: 'U+20BF', keywords: ['bitcoin', 'btc', 'crypto'] },
  { symbol: '¢', name: 'Cent Sign', category: 'Currency', unicode: 'U+00A2', keywords: ['cent', 'penny', 'money'] },
  { symbol: '₩', name: 'Won Sign', category: 'Currency', unicode: 'U+20A9', keywords: ['won', 'krw', 'money'] },
  { symbol: '₪', name: 'New Sheqel Sign', category: 'Currency', unicode: 'U+20AA', keywords: ['shekel', 'ils', 'money'] },
  { symbol: '₨', name: 'Rupee Sign', category: 'Currency', unicode: 'U+20A8', keywords: ['rupee', 'money'] },
  { symbol: '₱', name: 'Peso Sign', category: 'Currency', unicode: 'U+20B1', keywords: ['peso', 'php', 'money'] },
  { symbol: '₦', name: 'Naira Sign', category: 'Currency', unicode: 'U+20A6', keywords: ['naira', 'ngn', 'money'] },
  { symbol: '₴', name: 'Hryvnia Sign', category: 'Currency', unicode: 'U+20B4', keywords: ['hryvnia', 'uah', 'money'] },
  { symbol: '฿', name: 'Baht Sign', category: 'Currency', unicode: 'U+0E3F', keywords: ['baht', 'thb', 'money'] },

  // Punctuation (15 symbols)
  { symbol: '!', name: 'Exclamation Mark', category: 'Punctuation', unicode: 'U+0021', keywords: ['exclamation', 'important'] },
  { symbol: '?', name: 'Question Mark', category: 'Punctuation', unicode: 'U+003F', keywords: ['question', 'query'] },
  { symbol: '‽', name: 'Interrobang', category: 'Punctuation', unicode: 'U+203D', keywords: ['interrobang', 'question', 'exclamation'] },
  { symbol: '…', name: 'Horizontal Ellipsis', category: 'Punctuation', unicode: 'U+2026', keywords: ['ellipsis', 'dots', 'continuation'] },
  { symbol: '·', name: 'Middle Dot', category: 'Punctuation', unicode: 'U+00B7', keywords: ['dot', 'bullet', 'separator'] },
  { symbol: '•', name: 'Bullet', category: 'Punctuation', unicode: 'U+2022', keywords: ['bullet', 'point', 'list'] },
  { symbol: '‣', name: 'Triangular Bullet', category: 'Punctuation', unicode: 'U+2023', keywords: ['bullet', 'triangle'] },
  { symbol: '†', name: 'Dagger', category: 'Punctuation', unicode: 'U+2020', keywords: ['dagger', 'footnote'] },
  { symbol: '‡', name: 'Double Dagger', category: 'Punctuation', unicode: 'U+2021', keywords: ['dagger', 'footnote', 'double'] },
  { symbol: '§', name: 'Section Sign', category: 'Punctuation', unicode: 'U+00A7', keywords: ['section', 'paragraph'] },
  { symbol: '¶', name: 'Pilcrow', category: 'Punctuation', unicode: 'U+00B6', keywords: ['pilcrow', 'paragraph'] },
  { symbol: '©', name: 'Copyright Sign', category: 'Punctuation', unicode: 'U+00A9', keywords: ['copyright', 'legal'] },
  { symbol: '®', name: 'Registered Sign', category: 'Punctuation', unicode: 'U+00AE', keywords: ['registered', 'trademark'] },
  { symbol: '™', name: 'Trade Mark Sign', category: 'Punctuation', unicode: 'U+2122', keywords: ['trademark', 'tm'] },
  { symbol: '№', name: 'Numero Sign', category: 'Punctuation', unicode: 'U+2116', keywords: ['numero', 'number'] },

  // Shapes (15 symbols)
  { symbol: '■', name: 'Black Square', category: 'Shapes', unicode: 'U+25A0', keywords: ['square', 'black', 'filled'] },
  { symbol: '□', name: 'White Square', category: 'Shapes', unicode: 'U+25A1', keywords: ['square', 'white', 'outline'] },
  { symbol: '▪', name: 'Black Small Square', category: 'Shapes', unicode: 'U+25AA', keywords: ['square', 'black', 'small'] },
  { symbol: '▫', name: 'White Small Square', category: 'Shapes', unicode: 'U+25AB', keywords: ['square', 'white', 'small'] },
  { symbol: '●', name: 'Black Circle', category: 'Shapes', unicode: 'U+25CF', keywords: ['circle', 'black', 'filled'] },
  { symbol: '○', name: 'White Circle', category: 'Shapes', unicode: 'U+25CB', keywords: ['circle', 'white', 'outline'] },
  { symbol: '◆', name: 'Black Diamond', category: 'Shapes', unicode: 'U+25C6', keywords: ['diamond', 'black', 'filled'] },
  { symbol: '◇', name: 'White Diamond', category: 'Shapes', unicode: 'U+25C7', keywords: ['diamond', 'white', 'outline'] },
  { symbol: '▲', name: 'Black Up-Pointing Triangle', category: 'Shapes', unicode: 'U+25B2', keywords: ['triangle', 'up', 'black'] },
  { symbol: '△', name: 'White Up-Pointing Triangle', category: 'Shapes', unicode: 'U+25B3', keywords: ['triangle', 'up', 'white'] },
  { symbol: '▼', name: 'Black Down-Pointing Triangle', category: 'Shapes', unicode: 'U+25BC', keywords: ['triangle', 'down', 'black'] },
  { symbol: '▽', name: 'White Down-Pointing Triangle', category: 'Shapes', unicode: 'U+25BD', keywords: ['triangle', 'down', 'white'] },
  { symbol: '★', name: 'Black Star', category: 'Shapes', unicode: 'U+2605', keywords: ['star', 'black', 'filled'] },
  { symbol: '☆', name: 'White Star', category: 'Shapes', unicode: 'U+2606', keywords: ['star', 'white', 'outline'] },
  { symbol: '♥', name: 'Black Heart Suit', category: 'Shapes', unicode: 'U+2665', keywords: ['heart', 'love', 'black'] },
  { symbol: '♡', name: 'White Heart Suit', category: 'Shapes', unicode: 'U+2661', keywords: ['heart', 'love', 'white'] },
  { symbol: '▶', name: 'Black Right-Pointing Triangle', category: 'Shapes', unicode: 'U+25B6', keywords: ['triangle', 'play', 'right'] },
  { symbol: '◀', name: 'Black Left-Pointing Triangle', category: 'Shapes', unicode: 'U+25C0', keywords: ['triangle', 'left'] },
  { symbol: '►', name: 'Black Right-Pointing Pointer', category: 'Shapes', unicode: 'U+25BA', keywords: ['pointer', 'right'] },
  { symbol: '◄', name: 'Black Left-Pointing Pointer', category: 'Shapes', unicode: 'U+25C4', keywords: ['pointer', 'left'] },
  { symbol: '▬', name: 'Black Rectangle', category: 'Shapes', unicode: 'U+25AC', keywords: ['rectangle', 'bar'] },
  { symbol: '◊', name: 'Lozenge', category: 'Shapes', unicode: 'U+25CA', keywords: ['lozenge', 'diamond'] },
  { symbol: '◘', name: 'Inverse Bullet', category: 'Shapes', unicode: 'U+25D8', keywords: ['bullet', 'inverse'] },
  { symbol: '○', name: 'White Circle', category: 'Shapes', unicode: 'U+25CB', keywords: ['circle', 'white'] },
  { symbol: '◙', name: 'Inverse White Circle', category: 'Shapes', unicode: 'U+25D9', keywords: ['circle', 'inverse'] },
  { symbol: '◐', name: 'Circle with Left Half Black', category: 'Shapes', unicode: 'U+25D0', keywords: ['circle', 'half'] },
  { symbol: '◑', name: 'Circle with Right Half Black', category: 'Shapes', unicode: 'U+25D1', keywords: ['circle', 'half'] },
  { symbol: '◒', name: 'Circle with Lower Half Black', category: 'Shapes', unicode: 'U+25D2', keywords: ['circle', 'half'] },
  { symbol: '◓', name: 'Circle with Upper Half Black', category: 'Shapes', unicode: 'U+25D3', keywords: ['circle', 'half'] },
  { symbol: '◔', name: 'Circle with Upper Right Quadrant Black', category: 'Shapes', unicode: 'U+25D4', keywords: ['circle', 'quarter'] },
  { symbol: '◕', name: 'Circle with All but Upper Left Quadrant Black', category: 'Shapes', unicode: 'U+25D5', keywords: ['circle', 'quarter'] },
  { symbol: '⬛', name: 'Black Large Square', category: 'Shapes', unicode: 'U+2B1B', keywords: ['square', 'black', 'large'] },
  { symbol: '⬜', name: 'White Large Square', category: 'Shapes', unicode: 'U+2B1C', keywords: ['square', 'white', 'large'] },
  { symbol: '◼', name: 'Black Medium Square', category: 'Shapes', unicode: 'U+25FC', keywords: ['square', 'black', 'medium'] },
  { symbol: '◻', name: 'White Medium Square', category: 'Shapes', unicode: 'U+25FB', keywords: ['square', 'white', 'medium'] },
  { symbol: '◾', name: 'Black Medium Small Square', category: 'Shapes', unicode: 'U+25FE', keywords: ['square', 'black', 'small'] },
  { symbol: '◽', name: 'White Medium Small Square', category: 'Shapes', unicode: 'U+25FD', keywords: ['square', 'white', 'small'] },
  { symbol: '▮', name: 'Black Vertical Rectangle', category: 'Shapes', unicode: 'U+25AE', keywords: ['rectangle', 'vertical'] },
  { symbol: '▯', name: 'White Vertical Rectangle', category: 'Shapes', unicode: 'U+25AF', keywords: ['rectangle', 'vertical'] },

  // Greek Letters (50 symbols)
  { symbol: 'Α', name: 'Greek Capital Letter Alpha', category: 'Greek Letters', unicode: 'U+0391', keywords: ['alpha', 'greek'] },
  { symbol: 'α', name: 'Greek Small Letter Alpha', category: 'Greek Letters', unicode: 'U+03B1', keywords: ['alpha', 'greek'] },
  { symbol: 'Β', name: 'Greek Capital Letter Beta', category: 'Greek Letters', unicode: 'U+0392', keywords: ['beta', 'greek'] },
  { symbol: 'β', name: 'Greek Small Letter Beta', category: 'Greek Letters', unicode: 'U+03B2', keywords: ['beta', 'greek'] },
  { symbol: 'Γ', name: 'Greek Capital Letter Gamma', category: 'Greek Letters', unicode: 'U+0393', keywords: ['gamma', 'greek'] },
  { symbol: 'γ', name: 'Greek Small Letter Gamma', category: 'Greek Letters', unicode: 'U+03B3', keywords: ['gamma', 'greek'] },
  { symbol: 'Δ', name: 'Greek Capital Letter Delta', category: 'Greek Letters', unicode: 'U+0394', keywords: ['delta', 'greek'] },
  { symbol: 'δ', name: 'Greek Small Letter Delta', category: 'Greek Letters', unicode: 'U+03B4', keywords: ['delta', 'greek'] },
  { symbol: 'Ε', name: 'Greek Capital Letter Epsilon', category: 'Greek Letters', unicode: 'U+0395', keywords: ['epsilon', 'greek'] },
  { symbol: 'ε', name: 'Greek Small Letter Epsilon', category: 'Greek Letters', unicode: 'U+03B5', keywords: ['epsilon', 'greek'] },
  { symbol: 'Ζ', name: 'Greek Capital Letter Zeta', category: 'Greek Letters', unicode: 'U+0396', keywords: ['zeta', 'greek'] },
  { symbol: 'ζ', name: 'Greek Small Letter Zeta', category: 'Greek Letters', unicode: 'U+03B6', keywords: ['zeta', 'greek'] },
  { symbol: 'Η', name: 'Greek Capital Letter Eta', category: 'Greek Letters', unicode: 'U+0397', keywords: ['eta', 'greek'] },
  { symbol: 'η', name: 'Greek Small Letter Eta', category: 'Greek Letters', unicode: 'U+03B7', keywords: ['eta', 'greek'] },
  { symbol: 'Θ', name: 'Greek Capital Letter Theta', category: 'Greek Letters', unicode: 'U+0398', keywords: ['theta', 'greek'] },
  { symbol: 'θ', name: 'Greek Small Letter Theta', category: 'Greek Letters', unicode: 'U+03B8', keywords: ['theta', 'greek'] },
  { symbol: 'Ι', name: 'Greek Capital Letter Iota', category: 'Greek Letters', unicode: 'U+0399', keywords: ['iota', 'greek'] },
  { symbol: 'ι', name: 'Greek Small Letter Iota', category: 'Greek Letters', unicode: 'U+03B9', keywords: ['iota', 'greek'] },
  { symbol: 'Κ', name: 'Greek Capital Letter Kappa', category: 'Greek Letters', unicode: 'U+039A', keywords: ['kappa', 'greek'] },
  { symbol: 'κ', name: 'Greek Small Letter Kappa', category: 'Greek Letters', unicode: 'U+03BA', keywords: ['kappa', 'greek'] },
  { symbol: 'Λ', name: 'Greek Capital Letter Lambda', category: 'Greek Letters', unicode: 'U+039B', keywords: ['lambda', 'greek'] },
  { symbol: 'λ', name: 'Greek Small Letter Lambda', category: 'Greek Letters', unicode: 'U+03BB', keywords: ['lambda', 'greek'] },
  { symbol: 'Μ', name: 'Greek Capital Letter Mu', category: 'Greek Letters', unicode: 'U+039C', keywords: ['mu', 'greek'] },
  { symbol: 'μ', name: 'Greek Small Letter Mu', category: 'Greek Letters', unicode: 'U+03BC', keywords: ['mu', 'greek', 'micro'] },
  { symbol: 'Ν', name: 'Greek Capital Letter Nu', category: 'Greek Letters', unicode: 'U+039D', keywords: ['nu', 'greek'] },
  { symbol: 'ν', name: 'Greek Small Letter Nu', category: 'Greek Letters', unicode: 'U+03BD', keywords: ['nu', 'greek'] },
  { symbol: 'Ξ', name: 'Greek Capital Letter Xi', category: 'Greek Letters', unicode: 'U+039E', keywords: ['xi', 'greek'] },
  { symbol: 'ξ', name: 'Greek Small Letter Xi', category: 'Greek Letters', unicode: 'U+03BE', keywords: ['xi', 'greek'] },
  { symbol: 'Ο', name: 'Greek Capital Letter Omicron', category: 'Greek Letters', unicode: 'U+039F', keywords: ['omicron', 'greek'] },
  { symbol: 'ο', name: 'Greek Small Letter Omicron', category: 'Greek Letters', unicode: 'U+03BF', keywords: ['omicron', 'greek'] },
  { symbol: 'Π', name: 'Greek Capital Letter Pi', category: 'Greek Letters', unicode: 'U+03A0', keywords: ['pi', 'greek'] },
  { symbol: 'π', name: 'Greek Small Letter Pi', category: 'Greek Letters', unicode: 'U+03C0', keywords: ['pi', 'greek'] },
  { symbol: 'Ρ', name: 'Greek Capital Letter Rho', category: 'Greek Letters', unicode: 'U+03A1', keywords: ['rho', 'greek'] },
  { symbol: 'ρ', name: 'Greek Small Letter Rho', category: 'Greek Letters', unicode: 'U+03C1', keywords: ['rho', 'greek'] },
  { symbol: 'Σ', name: 'Greek Capital Letter Sigma', category: 'Greek Letters', unicode: 'U+03A3', keywords: ['sigma', 'greek'] },
  { symbol: 'σ', name: 'Greek Small Letter Sigma', category: 'Greek Letters', unicode: 'U+03C3', keywords: ['sigma', 'greek'] },
  { symbol: 'ς', name: 'Greek Small Letter Final Sigma', category: 'Greek Letters', unicode: 'U+03C2', keywords: ['sigma', 'final', 'greek'] },
  { symbol: 'Τ', name: 'Greek Capital Letter Tau', category: 'Greek Letters', unicode: 'U+03A4', keywords: ['tau', 'greek'] },
  { symbol: 'τ', name: 'Greek Small Letter Tau', category: 'Greek Letters', unicode: 'U+03C4', keywords: ['tau', 'greek'] },
  { symbol: 'Υ', name: 'Greek Capital Letter Upsilon', category: 'Greek Letters', unicode: 'U+03A5', keywords: ['upsilon', 'greek'] },
  { symbol: 'υ', name: 'Greek Small Letter Upsilon', category: 'Greek Letters', unicode: 'U+03C5', keywords: ['upsilon', 'greek'] },
  { symbol: 'Φ', name: 'Greek Capital Letter Phi', category: 'Greek Letters', unicode: 'U+03A6', keywords: ['phi', 'greek'] },
  { symbol: 'φ', name: 'Greek Small Letter Phi', category: 'Greek Letters', unicode: 'U+03C6', keywords: ['phi', 'greek'] },
  { symbol: 'Χ', name: 'Greek Capital Letter Chi', category: 'Greek Letters', unicode: 'U+03A7', keywords: ['chi', 'greek'] },
  { symbol: 'χ', name: 'Greek Small Letter Chi', category: 'Greek Letters', unicode: 'U+03C7', keywords: ['chi', 'greek'] },
  { symbol: 'Ψ', name: 'Greek Capital Letter Psi', category: 'Greek Letters', unicode: 'U+03A8', keywords: ['psi', 'greek'] },
  { symbol: 'ψ', name: 'Greek Small Letter Psi', category: 'Greek Letters', unicode: 'U+03C8', keywords: ['psi', 'greek'] },
  { symbol: 'Ω', name: 'Greek Capital Letter Omega', category: 'Greek Letters', unicode: 'U+03A9', keywords: ['omega', 'greek'] },
  { symbol: 'ω', name: 'Greek Small Letter Omega', category: 'Greek Letters', unicode: 'U+03C9', keywords: ['omega', 'greek'] },

  // Technical (30 symbols)
  { symbol: '⌘', name: 'Command Key', category: 'Technical', unicode: 'U+2318', keywords: ['command', 'mac', 'keyboard'] },
  { symbol: '⌥', name: 'Option Key', category: 'Technical', unicode: 'U+2325', keywords: ['option', 'alt', 'keyboard'] },
  { symbol: '⎋', name: 'Escape', category: 'Technical', unicode: 'U+238B', keywords: ['escape', 'esc', 'keyboard'] },
  { symbol: '⇧', name: 'Shift', category: 'Technical', unicode: 'U+21E7', keywords: ['shift', 'keyboard'] },
  { symbol: '⇪', name: 'Caps Lock', category: 'Technical', unicode: 'U+21EA', keywords: ['caps lock', 'keyboard'] },
  { symbol: '⌫', name: 'Delete Backwards', category: 'Technical', unicode: 'U+232B', keywords: ['delete', 'backspace', 'keyboard'] },
  { symbol: '⌦', name: 'Delete Forwards', category: 'Technical', unicode: 'U+2326', keywords: ['delete', 'forward', 'keyboard'] },
  { symbol: '⏎', name: 'Return', category: 'Technical', unicode: 'U+23CE', keywords: ['return', 'enter', 'keyboard'] },
  { symbol: '⎵', name: 'Space', category: 'Technical', unicode: 'U+23B5', keywords: ['space', 'spacebar', 'keyboard'] },
  { symbol: '⇥', name: 'Tab', category: 'Technical', unicode: 'U+21E5', keywords: ['tab', 'keyboard'] },
  { symbol: '⇤', name: 'Back Tab', category: 'Technical', unicode: 'U+21E4', keywords: ['back tab', 'keyboard'] },
  { symbol: '⌃', name: 'Control', category: 'Technical', unicode: 'U+2303', keywords: ['control', 'ctrl', 'keyboard'] },
  { symbol: '⎇', name: 'Alternate', category: 'Technical', unicode: 'U+2387', keywords: ['alt', 'alternate', 'keyboard'] },
  { symbol: '⏻', name: 'Power Symbol', category: 'Technical', unicode: 'U+23FB', keywords: ['power', 'on', 'off'] },
  { symbol: '⏼', name: 'Power On-Off Symbol', category: 'Technical', unicode: 'U+23FC', keywords: ['power', 'toggle'] },
  { symbol: '⏽', name: 'Power On Symbol', category: 'Technical', unicode: 'U+23FD', keywords: ['power', 'on'] },
  { symbol: '⏾', name: 'Power Sleep Symbol', category: 'Technical', unicode: 'U+23FE', keywords: ['power', 'sleep'] },
  { symbol: '⎀', name: 'Insert Symbol', category: 'Technical', unicode: 'U+2380', keywords: ['insert', 'keyboard'] },
  { symbol: '⌂', name: 'House', category: 'Technical', unicode: 'U+2302', keywords: ['home', 'house'] },
  { symbol: '⌨', name: 'Keyboard', category: 'Technical', unicode: 'U+2328', keywords: ['keyboard', 'type'] },
  { symbol: '🖱', name: 'Computer Mouse', category: 'Technical', unicode: 'U+1F5B1', keywords: ['mouse', 'computer'] },
  { symbol: '🖨', name: 'Printer', category: 'Technical', unicode: 'U+1F5A8', keywords: ['printer', 'print'] },
  { symbol: '⌚', name: 'Watch', category: 'Technical', unicode: 'U+231A', keywords: ['watch', 'time'] },
  { symbol: '⏰', name: 'Alarm Clock', category: 'Technical', unicode: 'U+23F0', keywords: ['alarm', 'clock'] },
  { symbol: '⏱', name: 'Stopwatch', category: 'Technical', unicode: 'U+23F1', keywords: ['stopwatch', 'timer'] },
  { symbol: '⏲', name: 'Timer Clock', category: 'Technical', unicode: 'U+23F2', keywords: ['timer', 'clock'] },
  { symbol: '⏳', name: 'Hourglass', category: 'Technical', unicode: 'U+23F3', keywords: ['hourglass', 'time', 'loading'] },
  { symbol: '⌛', name: 'Hourglass Done', category: 'Technical', unicode: 'U+231B', keywords: ['hourglass', 'done', 'time'] },
  { symbol: '⚙', name: 'Gear', category: 'Technical', unicode: 'U+2699', keywords: ['gear', 'settings', 'config'] },
  { symbol: '⚡', name: 'High Voltage', category: 'Technical', unicode: 'U+26A1', keywords: ['lightning', 'electric', 'power'] },
  { symbol: '🔋', name: 'Battery', category: 'Technical', unicode: 'U+1F50B', keywords: ['battery', 'power'] },
  { symbol: '🔌', name: 'Electric Plug', category: 'Technical', unicode: 'U+1F50C', keywords: ['plug', 'electric'] },
  { symbol: '💾', name: 'Floppy Disk', category: 'Technical', unicode: 'U+1F4BE', keywords: ['save', 'floppy', 'disk'] },
  { symbol: '💿', name: 'Optical Disk', category: 'Technical', unicode: 'U+1F4BF', keywords: ['cd', 'disk', 'optical'] },
  { symbol: '📀', name: 'DVD', category: 'Technical', unicode: 'U+1F4C0', keywords: ['dvd', 'disk'] },
  { symbol: '🖥', name: 'Desktop Computer', category: 'Technical', unicode: 'U+1F5A5', keywords: ['computer', 'desktop', 'pc'] },
  { symbol: '🖨', name: 'Printer', category: 'Technical', unicode: 'U+1F5A8', keywords: ['printer', 'print'] },
  { symbol: '⌨', name: 'Keyboard', category: 'Technical', unicode: 'U+2328', keywords: ['keyboard'] },
  { symbol: '📡', name: 'Satellite Antenna', category: 'Technical', unicode: 'U+1F4E1', keywords: ['satellite', 'antenna', 'signal'] },
  { symbol: '📶', name: 'Signal Strength', category: 'Technical', unicode: 'U+1F4F6', keywords: ['signal', 'wifi', 'bars'] },

  // Miscellaneous (15 symbols)
  { symbol: '✓', name: 'Check Mark', category: 'Miscellaneous', unicode: 'U+2713', keywords: ['check', 'yes', 'done'] },
  { symbol: '✔', name: 'Heavy Check Mark', category: 'Miscellaneous', unicode: 'U+2714', keywords: ['check', 'yes', 'done', 'bold'] },
  { symbol: '✗', name: 'Ballot X', category: 'Miscellaneous', unicode: 'U+2717', keywords: ['x', 'no', 'wrong'] },
  { symbol: '✘', name: 'Heavy Ballot X', category: 'Miscellaneous', unicode: 'U+2718', keywords: ['x', 'no', 'wrong', 'bold'] },
  { symbol: '☐', name: 'Ballot Box', category: 'Miscellaneous', unicode: 'U+2610', keywords: ['checkbox', 'unchecked', 'box'] },
  { symbol: '☑', name: 'Ballot Box with Check', category: 'Miscellaneous', unicode: 'U+2611', keywords: ['checkbox', 'checked', 'box'] },
  { symbol: '☒', name: 'Ballot Box with X', category: 'Miscellaneous', unicode: 'U+2612', keywords: ['checkbox', 'x', 'box'] },
  { symbol: '☼', name: 'White Sun with Rays', category: 'Miscellaneous', unicode: 'U+263C', keywords: ['sun', 'weather', 'bright'] },
  { symbol: '☾', name: 'Last Quarter Moon', category: 'Miscellaneous', unicode: 'U+263E', keywords: ['moon', 'night'] },
  { symbol: '☀', name: 'Black Sun with Rays', category: 'Miscellaneous', unicode: 'U+2600', keywords: ['sun', 'weather', 'sunny'] },
  { symbol: '☁', name: 'Cloud', category: 'Miscellaneous', unicode: 'U+2601', keywords: ['cloud', 'weather'] },
  { symbol: '☂', name: 'Umbrella', category: 'Miscellaneous', unicode: 'U+2602', keywords: ['umbrella', 'rain', 'weather'] },
  { symbol: '♠', name: 'Black Spade Suit', category: 'Miscellaneous', unicode: 'U+2660', keywords: ['spade', 'cards', 'poker'] },
  { symbol: '♣', name: 'Black Club Suit', category: 'Miscellaneous', unicode: 'U+2663', keywords: ['club', 'cards', 'poker'] },
  { symbol: '♦', name: 'Black Diamond Suit', category: 'Miscellaneous', unicode: 'U+2666', keywords: ['diamond', 'cards', 'poker'] },
];

export function searchSymbols(query: string, category: SymbolCategory = 'All'): Symbol[] {
  const lowerQuery = query.toLowerCase().trim();

  let filtered = category === 'All' ? symbols : symbols.filter(s => s.category === category);

  if (lowerQuery) {
    filtered = filtered.filter(s => s.name.toLowerCase().includes(lowerQuery) || s.keywords.some(k => k.toLowerCase().includes(lowerQuery)) || s.symbol.includes(lowerQuery));
  }

  return filtered;
}

export function getSymbolsByCategory(category: SymbolCategory): Symbol[] {
  if (category === 'All') return symbols;
  return symbols.filter(s => s.category === category);
}
